# Scaffolding generated by Casein v5.1.1.1

module Casein
  class AlertasController < Casein::CaseinController
    load_and_authorize_resource
    
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Alertas'
  		@alertas = Alerta.order(exibir_ate: :desc)
    end
  
    def show
      @casein_page_title = 'View alerta'
      @alerta = Alerta.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new alerta'
    	@alerta = Alerta.new
    end

    def create
      @alerta = Alerta.new alerta_params
    
      if @alerta.save
        flash[:notice] = 'Alerta created'
        redirect_to casein_alertas_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new alerta'
        render :action => :new
      end
    end

    def edit
      @alerta = Alerta.find params[:id]
    end
  
    def update
      @casein_page_title = 'Update alerta'
      
      @alerta = Alerta.find params[:id]
    
      if @alerta.update_attributes alerta_params
        flash[:notice] = 'Alerta has been updated'
        redirect_to casein_alertas_path
      else
        flash.now[:warning] = 'There were problems when trying to update this alerta'
        render :action => :edit
      end
    end
 
    def destroy
      @alerta = Alerta.find params[:id]

      @alerta.destroy
      flash[:notice] = 'Alerta has been deleted'
      redirect_to casein_alertas_path
    end
  
    private
      
      def alerta_params
        params.require(:alerta).permit(:titulo, :descricao, :exibir_ate, arquivos_attributes: [:id, :owner_id, :owner_type, :upload, :_destroy])
      end

  end
end