# Scaffolding generated by Casein v5.1.1.1

module Casein
  class AprofundamentoFuncionariosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Aprofundamento funcionarios'
  		@aprofundamento_funcionarios = AprofundamentoFuncionario.order(sort_order(:aprofundamento_id))
    end
  
    def show
      @casein_page_title = 'View aprofundamento funcionario'
      @aprofundamento_funcionario = AprofundamentoFuncionario.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new aprofundamento funcionario'
    	@aprofundamento_funcionario = AprofundamentoFuncionario.new
    end

    def create
      @aprofundamento_funcionario = AprofundamentoFuncionario.new aprofundamento_funcionario_params
    
      if @aprofundamento_funcionario.save
        flash[:notice] = 'Aprofundamento funcionario created'
        redirect_to casein_aprofundamento_funcionarios_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new aprofundamento funcionario'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update aprofundamento funcionario'
      
      @aprofundamento_funcionario = AprofundamentoFuncionario.find params[:id]
    
      if @aprofundamento_funcionario.update_attributes aprofundamento_funcionario_params
        flash[:notice] = 'Aprofundamento funcionario has been updated'
        redirect_to casein_aprofundamento_funcionarios_path
      else
        flash.now[:warning] = 'There were problems when trying to update this aprofundamento funcionario'
        render :action => :show
      end
    end
 
    def destroy
      @aprofundamento_funcionario = AprofundamentoFuncionario.find params[:id]

      @aprofundamento_funcionario.destroy
      flash[:notice] = 'Aprofundamento funcionario has been deleted'
      redirect_to casein_aprofundamento_funcionarios_path
    end
  
    private
      
      def aprofundamento_funcionario_params
        params.require(:aprofundamento_funcionario).permit(:aprofundamento_id, :funcionario_id)
      end

  end
end