# Scaffolding generated by Casein v5.1.1.1

module Casein
  class AprofundamentosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
    has_scope :cliente_id
    
    def index
      @casein_page_title = t('aprofundamentos.index.titulo')
      respond_to do |format|
        format.html
        format.json { render json: AprofundamentoDatatable.new(view_context) }
      end
    end
  
    def show
      @casein_page_title = t('aprofundamentos.show.titulo')
      @aprofundamento = Aprofundamento.find params[:id]
      @vazao_total = EntradaAgua.where("aprofundamento_id = #{@aprofundamento.id}").sum('vazao_aproximada')
    end
  
    def new
      @casein_page_title = t('aprofundamentos.new.titulo')
      @aprofundamento = Aprofundamento.new
      @aprofundamento.aprofundamento_funcionarios.build
      @aprofundamento.entradas_agua.build
      @aprofundamento.arquivos.build
    end

    def create
      @aprofundamento = Aprofundamento.new aprofundamento_params
    
      if @aprofundamento.save
        flash[:notice] = t('aprofundamentos.create.sucesso', data_inicio: @aprofundamento.data_inicio)
        
        if params["avancar"]
          redirect_to new_casein_vazao_agua_path(poco: @aprofundamento.poco_id)
        else
          redirect_to casein_aprofundamento_path(@aprofundamento)
        end
      else
        flash.now[:warning] = t('aprofundamentos.create.alerta')
        render :action => :new
      end
    end

    def edit
      @aprofundamento = Aprofundamento.find(params[:id])
      @aprofundamento.aprofundamento_funcionarios.build if @aprofundamento.aprofundamento_funcionarios.blank?
      @aprofundamento.entradas_agua.build if @aprofundamento.entradas_agua.blank?
      @aprofundamento.arquivos.build if @aprofundamento.arquivos.blank?
      @vazao_total = EntradaAgua.where("aprofundamento_id = #{@aprofundamento.id}").sum('vazao_aproximada')
    end
  
    def update
      @casein_page_title = 'Update aprofundamento'
      
      @aprofundamento = Aprofundamento.find params[:id]
    
      if @aprofundamento.update_attributes aprofundamento_params
        flash[:notice] = t('aprofundamentos.update.sucesso', data_inicio: @aprofundamento.data_inicio)
        
        if params["avancar"]
          @teste_vazao = VazaoAgua.where(aprofundamento_id: @aprofundamento.id).first

          if @teste_vazao.try(:id)
            redirect_to casein_vazao_agua_path(@teste_vazao)
          else
            redirect_to casein_aprofundamento_path(@aprofundamento)
          end
        else
          redirect_to casein_aprofundamento_path(@aprofundamento)
        end
      else
        flash.now[:warning] = t('aprofundamentos.update.alerta')
        render :action => :edit
      end
    end
 
    def destroy
      @aprofundamento = Aprofundamento.find params[:id]

      @aprofundamento.destroy
      flash[:notice] = t('aprofundamentos.destroy.sucesso')
      redirect_to casein_aprofundamentos_path
    end
  
    def filtro_ajax
      @aprofundamentos = apply_scopes(Aprofundamento).order(sort_order(:data_inicio))
    end

    private
      
      def aprofundamento_params
        params.require(:aprofundamento).permit(:observacao, :data_inicio, :data_fim, :poco_id, :profundidade_nova, :bitola_id, :maquina_id, aprofundamento_funcionarios_attributes: [:id, :aprofundamento_id, :funcionario_id, :_destroy], entradas_agua_attributes: [:id, :metragem, :vazao_aproximada, :poco_id, :aprofundamento_id, :_destroy], arquivos_attributes: [:id, :owner_id, :owner_type, :upload, :_destroy])
      end

  end
end