# Scaffolding generated by Casein v5.1.1.1

module Casein
  class ArquivosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Arquivos'
  		@arquivos = Arquivo.order(sort_order(:vazao_agua_id))
    end
  
    def show
      @casein_page_title = 'View arquivo'
      @arquivo = Arquivo.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new arquivo'
    	@arquivo = Arquivo.new
    end

    def create
      @arquivo = Arquivo.new arquivo_params
    
      if @arquivo.save
        flash[:notice] = 'Arquivo created'
        redirect_to casein_arquivos_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new arquivo'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update arquivo'
      
      @arquivo = Arquivo.find params[:id]
    
      if @arquivo.update_attributes arquivo_params
        flash[:notice] = 'Arquivo has been updated'
        redirect_to casein_arquivos_path
      else
        flash.now[:warning] = 'There were problems when trying to update this arquivo'
        render :action => :show
      end
    end
 
    def destroy
      @arquivo = Arquivo.find params[:id]

      @arquivo.destroy
      flash[:notice] = 'Arquivo has been deleted'
      redirect_to casein_arquivos_path
    end
  
    private
      
      def arquivo_params
        params.require(:arquivo).permit(:owner_id, :owner_type, :upload)
      end

  end
end