# Scaffolding generated by Casein v5.1.1.1

module Casein
  class BitolasController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('bitolas.index.titulo')
  		@bitolas = Bitola.order(sort_order(:descricao))
    end

    def show
      @casein_page_title = t('bitolas.show.titulo')
      @bitola = Bitola.find params[:id]
    end

    def new
      @casein_page_title = t('bitolas.new.titulo')
    	@bitola = Bitola.new
    end

    def create
      @bitola = Bitola.new bitola_params

      if @bitola.save
        flash[:notice] = t('bitolas.create.sucesso', descricao: @bitola.descricao)
        redirect_to casein_bitolas_path
      else
        flash.now[:warning] = t('bitolas.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('bitolas.update.titulo')

      @bitola = Bitola.find params[:id]

      if @bitola.update_attributes bitola_params
        flash[:notice] = t('bitolas.update.sucesso', descricao: @bitola.descricao)
        redirect_to casein_bitolas_path
      else
        flash.now[:warning] = t('bitolas.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @bitola = Bitola.find params[:id]

      @bitola.destroy
      flash[:notice] = t('bitolas.destroy.sucesso')
      redirect_to casein_bitolas_path
    end
    
    def adicionar
      @bitola = Bitola.create(descricao: params[:item])
    end

    private

      def bitola_params
        params.require(:bitola).permit(:descricao)
      end

  end
end
