# Scaffolding generated by Casein v5.1.1.1

module Casein
  class BombeadoresController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('bombeadores.index.titulo')
  		@bombeadores = Bombeador.order(sort_order(:descricao))
    end

    def show
      @casein_page_title = t('bombeadores.show.titulo')
      @bombeador = Bombeador.find params[:id]
    end

    def new
      @casein_page_title = t('bombeadores.new.titulo')
    	@bombeador = Bombeador.new
    end

    def create
      @bombeador = Bombeador.new bombeador_params

      if @bombeador.save
        flash[:notice] = t('bombeadores.create.sucesso', descricao: @bombeador.descricao)
        redirect_to casein_bombeadores_path
      else
        flash.now[:warning] = t('bombeadores.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('bombeadores.update.titulo')

      @bombeador = Bombeador.find params[:id]

      if @bombeador.update_attributes bombeador_params
        flash[:notice] = t('bombeadores.update.sucesso', descricao: @bombeador.descricao)
        redirect_to casein_bombeadores_path
      else
        flash.now[:warning] = t('bombeadores.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @bombeador = Bombeador.find params[:id]

      @bombeador.destroy
      flash[:notice] = t('bombeadores.destroy.sucesso')
      redirect_to casein_bombeadores_path
    end

    private

      def bombeador_params
        params.require(:bombeador).permit(:descricao)
      end

  end
end
