# Scaffolding generated by Casein v5.1.1.1

module Casein
  class BombasController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('bombas.index.titulo')
  		@bombas = Bomba.order(sort_order(:observacao))
    end

    def show
      @casein_page_title = t('bombas.show.titulo')
      @bomba = Bomba.find params[:id]
    end

    def new
      @casein_page_title = t('bombas.new.titulo')
    	@bomba = Bomba.new
    end

    def create
      @bomba = Bomba.new bomba_params

      if @bomba.save
        flash[:notice] = t('bombas.create.sucesso', observacao: @bomba.observacao)
        redirect_to casein_bombas_path
      else
        flash.now[:warning] = t('bombas.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('clientes.update.titulo')

      @bomba = Bomba.find params[:id]

      if @bomba.update_attributes bomba_params
        flash[:notice] = t('bombas.update.sucesso', observacao: @bomba.observacao)
        redirect_to casein_bombas_path
      else
        flash.now[:warning] = t('bombas.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @bomba = Bomba.find params[:id]

      @bomba.destroy
      flash[:notice] = t('bombas.destroy.sucesso')
      redirect_to casein_bombas_path
    end

    private

      def bomba_params
        params.require(:bomba).permit(:observacao, :modelo_bomba_id, :estagio_id, :hp_id, :energia_id, :motor_id, :bombeador_id, :instalacao_id)
      end

  end
end
