# Scaffolding generated by Casein v5.1.1.1

module Casein
  class CargosController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
    has_scope :id

    def index
      @casein_page_title = t('cargos.index.titulo')
  		@cargos = Cargo.order(sort_order(:descricao))
    end

    def show
      @casein_page_title = t('cargos.show.titulo')
      @cargo = Cargo.find params[:id]
    end

    def new
      @casein_page_title = t('cargos.new.titulo')
    	@cargo = Cargo.new
    end

    def create
      @cargo = Cargo.new cargo_params

      if @cargo.save
        flash[:notice] = t('cargos.create.sucesso', descricao: @cargo.descricao)
        redirect_to casein_cargos_path
      else
        flash.now[:warning] = t('cargos.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('cargos.update.titulo')

      @cargo = Cargo.find params[:id]

      if @cargo.update_attributes cargo_params
        flash[:notice] = t('cargos.update.sucesso', descricao: @cargo.descricao)
        redirect_to casein_cargos_path
      else
        flash.now[:warning] = t('cargos.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @cargo = Cargo.find params[:id]

      @cargo.destroy
      flash[:notice] = t('cargos.destroy.sucesso')
      redirect_to casein_cargos_path
    end

    def filtro_ajax
      @cargos = apply_scopes(Cargo).order(sort_order(:descricao))
    end

    private

      def cargo_params
        params.require(:cargo).permit(:descricao)
      end

  end
end
