# Scaffolding generated by Casein v5.1.1.1

module Casein
  class CoordenadasController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = 'Coordenadas'
  		@coordenadas = Coordenada.order(sort_order(:ponto_a_latitude))
    end

    def show
      @casein_page_title = 'View coordenada'
      @coordenada = Coordenada.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new coordenada'
    	@coordenada = Coordenada.new
    end

    def create
      @coordenada = Coordenada.new coordenada_params

      if @coordenada.save
        flash[:notice] = 'Coordenada created'
        redirect_to casein_coordenadas_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new coordenada'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update coordenada'

      @coordenada = Coordenada.find params[:id]

      if @coordenada.update_attributes coordenada_params
        flash[:notice] = 'Coordenada has been updated'
        redirect_to casein_coordenadas_path
      else
        flash.now[:warning] = 'There were problems when trying to update this coordenada'
        render :action => :show
      end
    end

    def destroy
      @coordenada = Coordenada.find params[:id]

      @coordenada.destroy
      flash[:notice] = 'Coordenada has been deleted'
      redirect_to casein_coordenadas_path
    end

    private

      def coordenada_params
        params.require(:coordenada).permit(:latitude, :longitude, :zona, :poco_id)
      end

  end
end
