# Scaffolding generated by Casein v5.1.1.1

module Casein
  class EnergiasController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('energias.index.titulo')
  		@energias = Energia.order(sort_order(:descricao))
    end

    def show
      @casein_page_title = t('energias.show.titulo')
      @energia = Energia.find params[:id]
    end

    def new
      @casein_page_title = t('energias.new.titulo')
    	@energia = Energia.new
    end

    def create
      @energia = Energia.new energia_params

      if @energia.save
        flash[:notice] = t('energias.create.sucesso', descricao: @energia.descricao)
        redirect_to casein_energias_path
      else
        flash.now[:warning] = t('energias.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('energias.update.titulo')

      @energia = Energia.find params[:id]

      if @energia.update_attributes energia_params
        flash[:notice] = t('energias.update.sucesso', descricao: @energia.descricao)
        redirect_to casein_energias_path
      else
        flash.now[:warning] = t('energias.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @energia = Energia.find params[:id]

      @energia.destroy
      flash[:notice] = t('energias.destroy.sucesso')
      redirect_to casein_energias_path
    end

    def adicionar
      @energia = Energia.create(descricao: params[:item])
      @target = "select_energia"
    end

    private

      def energia_params
        params.require(:energia).permit(:descricao)
      end

  end
end
