# Scaffolding generated by Casein v5.1.1.1

module Casein
  class EntradasAguaController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = 'Entradas agua'
  		@entradas_agua = EntradaAgua.order(sort_order(:metragem))
    end

    def show
      @casein_page_title = 'View entrada agua'
      @entrada_agua = EntradaAgua.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new entrada agua'
    	@entrada_agua = EntradaAgua.new
    end

    def create
      @entrada_agua = EntradaAgua.new entrada_agua_params

      if @entrada_agua.save
        flash[:notice] = 'Entrada agua created'
        redirect_to casein_entradas_agua_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new entrada agua'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update entrada agua'

      @entrada_agua = EntradaAgua.find params[:id]

      if @entrada_agua.update_attributes entrada_agua_params
        flash[:notice] = 'Entrada agua has been updated'
        redirect_to casein_entradas_agua_path
      else
        flash.now[:warning] = 'There were problems when trying to update this entrada agua'
        render :action => :show
      end
    end

    def destroy
      @entrada_agua = EntradaAgua.find params[:id]

      @entrada_agua.destroy
      flash[:notice] = 'Entrada agua has been deleted'
      redirect_to casein_entradas_agua_path
    end

    private

      def entrada_agua_params
        params.require(:entrada_agua).permit(:metragem, :vazao_aproximada, :poco_id, :aprofundamento_id)
      end

  end
end
