# Scaffolding generated by Casein v5.1.1.1

module Casein
  class EstagiosController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('estagios.index.titulo')
  		@estagios = Estagio.order(sort_order(:descricao))
    end

    def show
      @casein_page_title = t('estagios.show.titulo')
      @estagio = Estagio.find params[:id]
    end

    def new
      @casein_page_title = t('estagios.new.titulo')
    	@estagio = Estagio.new
    end

    def create
      @estagio = Estagio.new estagio_params

      if @estagio.save
        flash[:notice] = t('estagios.create.sucesso', descricao: @estagio.descricao)
        redirect_to casein_estagios_path
      else
        flash.now[:warning] = t('estagios.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('estagios.update.titulo')

      @estagio = Estagio.find params[:id]

      if @estagio.update_attributes estagio_params
        flash[:notice] = t('estagios.update.sucesso', descricao: @estagio.descricao)
        redirect_to casein_estagios_path
      else
        flash.now[:warning] = t('estagios.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @estagio = Estagio.find params[:id]

      @estagio.destroy
      flash[:notice] = t('estagios.destroy.sucesso')
      redirect_to casein_estagios_path
    end

    def adicionar
      @estagio = Estagio.create(descricao: params[:item])
      @target = "select_estagio"
    end

    private

      def estagio_params
        params.require(:estagio).permit(:descricao)
      end

  end
end
