# Scaffolding generated by Casein v5.1.1.1

module Casein
  class FornecedoresController < Casein::CaseinController
    load_and_authorize_resource
    
    has_scope :nome

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('fornecedores.index.titulo')

      if params[:nome]
        @fornecedores = apply_scopes(Fornecedor).order(sort_order(:nome))
      else
        @fornecedores = Fornecedor.joins(:pessoa).order(sort_order(:nome))
      end
    end

    def show
      @casein_page_title = t('fornecedores.show.titulo')
      @fornecedor = Fornecedor.find params[:id]
      @pessoa = @fornecedor.pessoa
      @pessoa.build_pessoa_fisica unless @pessoa.pessoa_fisica
      @pessoa.build_pessoa_juridica unless @pessoa.pessoa_juridica
      @pessoa.build_pessoa_endereco unless @pessoa.pessoa_endereco
      @pessoa.pessoas_contatos.build
    end

    def new
      @casein_page_title = t('fornecedores.new.titulo')
    	@fornecedor = Fornecedor.new
      @pessoa = @fornecedor.build_pessoa
      @pessoa.build_pessoa_fisica
      @pessoa.build_pessoa_juridica
      @pessoa.build_pessoa_endereco
      @pessoa.pessoas_contatos.build
    end

    def create
      @fornecedor = Fornecedor.new fornecedor_params

      if @fornecedor.save
        flash[:notice] = t('fornecedores.create.sucesso', nome: @fornecedor.pessoa.nome)
        redirect_to casein_fornecedores_path
      else
        flash.now[:warning] = t('fornecedores.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('fornecedores.update.titulo')

      @fornecedor = Fornecedor.find params[:id]

      if @fornecedor.update_attributes fornecedor_params
        flash[:notice] = t('fornecedores.update.sucesso', nome: @fornecedor.pessoa.nome)
        redirect_to casein_fornecedores_path
      else
        flash.now[:warning] = t('fornecedores.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @fornecedor = Fornecedor.find params[:id]

      @fornecedor.destroy
      flash[:notice] = t('fornecedores.destroy.sucesso')
      redirect_to casein_fornecedores_path
    end

    private

      def fornecedor_params
        params.require(:fornecedor).permit(:pessoa, :nome_contato, :cargo_id, :observacoes, pessoa_attributes: [:id, :nome])
      end

  end
end
