# Scaffolding generated by Casein v5.1.1.1

module Casein
  class FuncionariosController < Casein::CaseinController
    load_and_authorize_resource
    has_scope :nome

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('funcionarios.index.titulo')

      @funcionarios = Funcionario.joins(:pessoa).order(sort_order(:nome))

      respond_to do |format|
        format.html
        format.js
      end
    end

    def show
      @casein_page_title = t('funcionarios.show.titulo')
      @funcionario = Funcionario.find params[:id]
      # @pessoa = @funcionario.pessoa
      # @pessoa.build_pessoa_fisica unless @pessoa.pessoa_fisica
      # @pessoa.build_pessoa_juridica unless @pessoa.pessoa_juridica
      # @pessoa.build_pessoa_endereco unless @pessoa.pessoa_endereco
      # @pessoa.pessoas_contatos.build
    end

    def edit
      @funcionario = Funcionario.find params[:id]

    end

    def new
      @casein_page_title = t('funcionarios.new.titulo')
    	@funcionario = Funcionario.new
      @funcionario.build_pessoa
      # @pessoa = @funcionario.build_pessoa
      # @pessoa.build_pessoa_fisica
      # @pessoa.build_pessoa_juridica
      # @pessoa.build_pessoa_endereco
      # @pessoa.pessoas_contatos.build
    end

    def create
      @funcionario = Funcionario.new funcionario_params

      if @funcionario.save
        if params[:senha].present?
          Funcionario.create_app_user(@funcionario.id, @funcionario.email, @funcionario.use_app, params[:senha].to_s)
        end
        flash[:notice] = t('funcionarios.create.sucesso', nome: @funcionario.pessoa.nome)
        redirect_to casein_funcionario_path(@funcionario)
      else
        @funcionario.build_pessoa if @funcionario.pessoa.blank?
        flash.now[:warning] = t('funcionarios.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('funcionarios.update.titulo')

      @funcionario = Funcionario.find params[:id]
      if @funcionario.update_attributes funcionario_params
        if params[:senha].present?
          Funcionario.handle_app_user(@funcionario.id, @funcionario.email, @funcionario.use_app, params[:senha].to_s)
        end

        flash[:notice] = t('funcionarios.update.sucesso', nome: @funcionario.pessoa.nome)
        redirect_to casein_funcionario_path(@funcionario)
      else
        flash.now[:warning] = t('funcionarios.update.alerta')
        render :action => :edit
      end
    end

    def destroy
      @funcionario = Funcionario.find params[:id]

      @funcionario.destroy
      flash[:notice] = t('funcionarios.destroy.sucesso')
      redirect_to casein_funcionarios_path
    end

    def adicionar
      @pessoa = Pessoa.create(nome: params[:item])
      @funcionario = Funcionario.create(pessoa_id: @pessoa.id)
      @target = "select_funcionario_#{params[:index]}"
    end

    private

      def funcionario_params
        params.require(:funcionario).permit(:pessoa, :cargo_id, :carteira_profissional, :data_admissao, :data_demissao, :use_app,:email, :curriculo, :cor, pessoa_attributes: [:id, :nome])
      end

  end
end
