# Scaffolding generated by Casein v5.1.1.1

module Casein
  class HpsController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('hps.index.titulo')
  		@hps = Hp.order(sort_order(:descricao))
    end

    def show
      @casein_page_title = t('hps.show.titulo')
      @hp = Hp.find params[:id]
    end

    def new
      @casein_page_title = t('hps.new.titulo')
    	@hp = Hp.new
    end

    def create
      @hp = Hp.new hp_params

      if @hp.save
        flash[:notice] = t('hps.create.sucesso', descricao: @hp.descricao)
        redirect_to casein_hps_path
      else
        flash.now[:warning] = t('hps.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('hps.update.titulo')

      @hp = Hp.find params[:id]

      if @hp.update_attributes hp_params
        flash[:notice] = t('hps.update.sucesso', descricao: @hp.descricao)
        redirect_to casein_hps_path
      else
        flash.now[:warning] = t('hps.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @hp = Hp.find params[:id]

      @hp.destroy
      flash[:notice] = t('hps.destroy.sucesso')
      redirect_to casein_hps_path
    end

    private

      def hp_params
        params.require(:hp).permit(:descricao)
      end

  end
end
