# Scaffolding generated by Casein v5.1.1.1

module Casein
  class InstalacoesController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    has_scope :funcionario_id
    has_scope :acesso
    has_scope :guincho
    has_scope :energia_id
    has_scope :profundidade, :using => [:profundidade_inicial, :profundidade_final], :type => :hash
    has_scope :vazao, :using => [:vazao_inicial, :vazao_final], :type => :hash
    has_scope :cliente_id

    def index
      @casein_page_title = t('instalacoes.index.titulo')
      respond_to do |format|
        format.html
        format.json { render json: InstalacaoDatatable.new(view_context) }
      end
    end

    def show
      @casein_page_title = t('instalacoes.show.titulo')
      @instalacao = Instalacao.find params[:id]
    end

    def new
      @casein_page_title = t('instalacoes.new.titulo')
    	@instalacao = Instalacao.new
      @instalacao.instalacao_funcionarios.build
      @instalacao.arquivos.build
      # @instalacao.instalacao_poco_equipamentos.build
      # @instalacao.instalacao_adutora_equipamentos.build
      # @instalacao.instalacao_distribuicao_equipamentos.build
      @instalacao.build_bomba
    end

    def create
      @instalacao = Instalacao.new instalacao_params

      if @instalacao.save
        @instalacao.poco.update(periodo_manutencao: @instalacao.periodo_manutencao)
        flash[:notice] = t('instalacoes.create.sucesso', id: @instalacao.id)
        redirect_to casein_instalacao_path(@instalacao)
      else
        @instalacao.build_bomba unless @instalacao.bomba
        @instalacao.arquivos.destroy_all
        flash.now[:warning] = t('instalacoes.create.alerta')
        render :action => :new
      end
    end

    def edit
      @instalacao = Instalacao.find params[:id]
      @instalacao.instalacao_funcionarios.build if @instalacao.instalacao_funcionarios.blank?
      @instalacao.arquivos.build if @instalacao.arquivos.blank?
      # @instalacao.instalacao_poco_equipamentos.build if @instalacao.instalacao_poco_equipamentos.blank?
      # @instalacao.instalacao_adutora_equipamentos.build if @instalacao.instalacao_adutora_equipamentos.blank?
      # @instalacao.instalacao_distribuicao_equipamentos.build if @instalacao.instalacao_distribuicao_equipamentos.blank?
      @instalacao.build_bomba unless @instalacao.bomba
    end

    def update
      @instalacao = Instalacao.find params[:id]

      if @instalacao.update_attributes instalacao_params
        @instalacao.poco.update(periodo_manutencao: @instalacao.periodo_manutencao)
        flash[:notice] = t('instalacoes.update.sucesso', id: @instalacao.id)
        redirect_to casein_instalacao_path(@instalacao)
      else
        @instalacao.build_bomba unless @instalacao.bomba
        flash.now[:warning] = t('instalacoes.update.alerta')
        render :action => :edit
      end
    end

    def destroy
      @instalacao = Instalacao.find params[:id]

      @instalacao.destroy
      flash[:notice] = t('instalacoes.destroy.sucesso')
      redirect_to casein_instalacoes_path
    end

    def filtro_relatorio
      params[:profundidade] ||= {}
      params[:vazao] ||= {}
      if  params[:vazao][:vazao_inicial] && params[:vazao][:vazao_inicial] != '' || params[:vazao][:vazao_final] && params[:vazao][:vazao_final] != '' || params[:profundidade][:profundidade_inicial] && params[:profundidade][:profundidade_inicial] != '' || params[:profundidade][:profundidade_final] && params[:profundidade][:profundidade_final] != '' || params[:energia_id] && params[:energia_id] != '' || params[:funcionario_id] && params[:funcionario_id] != '' || params[:acesso] && params[:acesso] != '' || params[:guincho] && params[:guincho] != ''
        @instalacoes = apply_scopes(Instalacao).all

        respond_to do |format|
          format.html
          format.pdf do
            render  template: "casein/instalacoes/imprimir_instalacao",
                handlers: [:erb],
                formats: [:pdf],
                page_size: "A3",
                pdf: "instalacao_#{Time.zone.now.to_s}",
                layout: 'layouts/pdf/pdf.html',
                header: {:html => {:template => 'layouts/pdf/header', handlers: [:erb], formats: [:pdf]}, :spacing => 8, :line => false},
                footer: {:html => {:template => 'layouts/pdf/footer', handlers: [:erb], formats: [:pdf]}, :line => false},
                margin: { :bottom => 20, :top => 35}
          end
        end
      end
    end

    def filtro_ajax
      @instalacoes = apply_scopes(Instalacao).order(sort_order(:poco_id))
    end

    private

      def instalacao_params
        params.require(:instalacao).permit(:data_instalacao_inicio, :poco_id, :acesso, :periodo_manutencao, :guincho, :possui_instalacao, :profundidade_bomba, :vazao_bomba, :nivel_dinamico, :perca_carga, :altura_nanometrica, :desnivel, :nivel_estatico, :distancia_poco_caixa, :bomba_id, :aprofundamento_id, instalacao_funcionarios_attributes: [:id, :instalacao_id, :funcionario_id, :_destroy], arquivos_attributes: [:id, :owner_id, :owner_type, :upload, :_destroy], bomba_attributes: [:id, :observacao, :modelo_bomba_id, :estagio_id, :hp_id, :energia_id, :motor_id, :bombeador_id, :instalacao_id, :_destroy], instalacao_poco_equipamentos_attributes: [:id, :produto_id, :quantidade, :observacao, :instalacao_id, :_destroy], instalacao_adutora_equipamentos_attributes: [:id, :produto_id, :quantidade, :observacao, :instalacao_id, :_destroy], instalacao_distribuicao_equipamentos_attributes: [:id, :produto_id, :quantidade, :observacao, :instalacao_id, :_destroy])
      end

  end
end