# Scaffolding generated by Casein v5.1.1.1

module Casein
  class InstalacaoFuncionariosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Instalacao funcionarios'
  		@instalacao_funcionarios = InstalacaoFuncionario.order(sort_order(:instalacao_id))
    end
  
    def show
      @casein_page_title = 'View instalacao funcionario'
      @instalacao_funcionario = InstalacaoFuncionario.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new instalacao funcionario'
    	@instalacao_funcionario = InstalacaoFuncionario.new
    end

    def create
      @instalacao_funcionario = InstalacaoFuncionario.new instalacao_funcionario_params
    
      if @instalacao_funcionario.save
        flash[:notice] = 'Instalacao funcionario created'
        redirect_to casein_instalacao_funcionarios_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new instalacao funcionario'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update instalacao funcionario'
      
      @instalacao_funcionario = InstalacaoFuncionario.find params[:id]
    
      if @instalacao_funcionario.update_attributes instalacao_funcionario_params
        flash[:notice] = 'Instalacao funcionario has been updated'
        redirect_to casein_instalacao_funcionarios_path
      else
        flash.now[:warning] = 'There were problems when trying to update this instalacao funcionario'
        render :action => :show
      end
    end
 
    def destroy
      @instalacao_funcionario = InstalacaoFuncionario.find params[:id]

      @instalacao_funcionario.destroy
      flash[:notice] = 'Instalacao funcionario has been deleted'
      redirect_to casein_instalacao_funcionarios_path
    end
  
    private
      
      def instalacao_funcionario_params
        params.require(:instalacao_funcionario).permit(:instalacao_id, :funcionario_id)
      end

  end
end