# Scaffolding generated by Casein v5.1.1.1

module Casein
  class InstalacaoPocoEquipamentosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def create
      @instalacao_poco_equipamento = InstalacaoPocoEquipamento.new instalacao_poco_equipamento_params
    
      if @instalacao_poco_equipamento.save
        @instalacao = @instalacao_poco_equipamento.instalacao

        flash[:notice] = 'Registro cadastrado'
        respond_to do |format|
          format.html {
            redirect_to casein_instalacao_poco_equipamentos_path
          }
          format.json
          format.js
        end
      else
        flash.now[:warning] = 'There were problems when trying to create'
        respond_to do |format|
          format.html {
            render :action => :new
          }
          format.json
          format.js
        end
      end
    end
  
    def update
      @casein_page_title = 'Atualizar'
      
      @instalacao_poco_equipamento = InstalacaoPocoEquipamento.find params[:id]
    
      if @instalacao_poco_equipamento.update_attributes instalacao_poco_equipamento_params
        flash[:notice] = 'Registro atualizado'
        redirect_to casein_instalacao_path(@instalacao_poco_equipamento.instalacao)
      else
        flash.now[:warning] = 'There were problems when trying to update this'
        render :action => :show
      end
    end
 
    def destroy
      @instalacao_poco_equipamento = InstalacaoPocoEquipamento.find_by_id params[:id]

      if @instalacao_poco_equipamento.blank?
        respond_to do |format|
          format.js
          format.json
        end
      else
        @instalacao = @instalacao_poco_equipamento.instalacao
        @instalacao_poco_equipamento.destroy
        
        flash[:notice] = 'Registro apagado'
        respond_to do |format|
          format.html {redirect_to casein_instalacao_path(@instalacao)}
          format.js
          format.json
        end
      end
    end

    # def cadastro_ajax
    #   @instalacao = Instalacao.find(params[:instalacao_id])
    #   @operacao_produto = InstalacaoPocoEquipamento.create(produto_id: params[:produto_id], quantidade: params[:quantidade], observacao: params[:observacao], instalacao_id: @instalacao.id)
    # end
  
    private
      
      def instalacao_poco_equipamento_params
        params.require(:instalacao_poco_equipamento).permit(:instalacao_id, :produto_id, :quantidade, :observacao)
      end
  end
end