# Scaffolding generated by Casein v5.1.1.1

module Casein
  class InstalacaoDistribuicaoEquipamentosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def create
      @instalacao_distribuicao_equipamento = InstalacaoDistribuicaoEquipamento.new instalacao_distribuicao_equipamento_params
    
      if @instalacao_distribuicao_equipamento.save
        flash[:notice] = 'Registro cadastrado'
        redirect_to casein_instalacao_distribuicao_equipamentos_path
      else
        flash.now[:warning] = 'There were problems when trying to create'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Atualizar'
      
      @instalacao_distribuicao_equipamento = InstalacaoDistribuicaoEquipamento.find params[:id]
    
      if @instalacao_distribuicao_equipamento.update_attributes instalacao_distribuicao_equipamento_params
        flash[:notice] = 'Registro atualizado'
        redirect_to casein_instalacao_path(@instalacao_distribuicao_equipamento.instalacao)
      else
        flash.now[:warning] = 'There were problems when trying to update this'
        render :action => :show
      end
    end
 
    def destroy
      @instalacao_distribuicao_equipamento = InstalacaoDistribuicaoEquipamento.find params[:id]
      @instalacao = Instalacao.find(@instalacao_distribuicao_equipamento.instalacao_id)

      @instalacao_distribuicao_equipamento.destroy
      flash[:notice] = 'Registro apagado'
      respond_to do |format|
        format.html {redirect_to casein_instalacao_path(@instalacao)}
        format.js
      end
    end

    # def cadastro_ajax
    #   @instalacao = Instalacao.find(params[:instalacao_id])
    #   @operacao_produto = InstalacaoDistribuicaoEquipamento.create(produto_id: params[:produto_id], quantidade: params[:quantidade], observacao: params[:observacao], instalacao_id: @instalacao.id)
    # end
  
    private
      
      def instalacao_distribuicao_equipamento_params
        params.require(:instalacao_distribuicao_equipamento).permit(:instalacao_id, :produto_id, :quantidade, :observacao)
      end
  end
end