# Scaffolding generated by Casein v5.1.1.1

module Casein
  class ManutencaosController < Casein::CaseinController
    load_and_authorize_resource

    has_scope :codigo

    def new_arquivo
      @manutencao = Manutencao.find(params[:id])
      @manutencao.arquivos.create(upload: params[:upload], nome: params[:nome])

      respond_to do |format|
        flash[:notice] = 'Arquivo enviado com sucesso!'
        format.html { redirect_to casein_ordem_servicos_path }
      end
    end

    def new_arquivo_show
      @manutencao = Manutencao.find(params[:id])
      @manutencao.arquivos.create(upload: params[:upload], nome: params[:nome])
      @os = OrdemServico.find(@manutencao.ordem_servico_id)

      respond_to do |format|
        flash[:notice] = 'Arquivo enviado com sucesso!'
        format.html { redirect_to casein_ordem_servico_path(@os.id)}
      end
    end

    def new_arquivo_show_manut
      @manutencao = Manutencao.find(params[:id])
      @manutencao.arquivos.create(upload: params[:upload], nome: params[:nome])

      respond_to do |format|
        flash[:notice] = 'Arquivo enviado com sucesso!'
        format.html { redirect_to casein_manutencao_path(@manutencao.id) }
      end
    end

    def index
      @casein_page_title = t('manutencaos.index.titulo')

      respond_to do |format|
        format.html
        format.json { render json: ManutencaoDatatable.new(view_context) }
      end
    end

    def show
      @casein_page_title = t('manutencaos.show.titulo')
      @manutencao = Manutencao.find params[:id]
      #busca a instalacao para poder listar os equipamentos
      @instalacao = Instalacao.where(poco: @manutencao.poco).last

      if @session_user.usuario_cidades.where(cidade_id: @manutencao.poco.cidade_id).blank? && !@session_user.is_admin?
        redirect_to root_url
      end
    end

    def new
      @casein_page_title = t('manutencaos.new.titulo')
    	@manutencao = Manutencao.new
      @manutencao.arquivos.build
      @manutencao.manutencao_checklists.build
      @manutencao.manutencao_produtos.build
      manutencao_servicos = @manutencao.manutencao_servicos.build
      manutencao_servicos.manutencao_funcionarios.build
      manutencao_servicos.manutencao_servico_itens.build
    end

    def create
      @manutencao = Manutencao.new manutencao_params

      if @manutencao.save
          flash[:notice] = t('manutencaos.create.sucesso', id: @manutencao.poco_id)
          redirect_to casein_manutencao_path(@manutencao)
      else
        flash.now[:warning] = t('manutencaos.create.alerta')
        render :action => :new
      end
    end

    def edit
      @manutencao = Manutencao.find params[:id]

      if @session_user.usuario_cidades.where(cidade_id: @manutencao.poco.cidade_id).blank? && !@session_user.is_admin?
        redirect_to root_url
      else
        @manutencao.arquivos.build if @manutencao.arquivos.blank?
        @manutencao.manutencao_checklists.build if @manutencao.manutencao_checklists.blank?
        @manutencao.manutencao_produtos.build if @manutencao.manutencao_produtos.blank?
        if @manutencao.manutencao_servicos.blank?
          manutencao_servicos = @manutencao.manutencao_servicos.build
          manutencao_servicos.manutencao_funcionarios.build
          manutencao_servicos.manutencao_servico_itens.build
        end

        #busca a instalacao para poder adicionar os equipamentos
        @instalacao = Instalacao.where(poco: @manutencao.poco).last
        @nova_instalacao = InstalacaoPocoEquipamento.new
      end
    end

    def update
      @casein_page_title = 'Update manutencao'

      @manutencao = Manutencao.find params[:id]

      if @session_user.usuario_cidades.where(cidade_id: @manutencao.poco.cidade_id).blank? && !@session_user.is_admin?
        redirect_to root_url
      else
        if @manutencao.update_attributes manutencao_params
          flash[:notice] = t('manutencaos.update.sucesso', id: @manutencao.poco_id)
          redirect_to casein_manutencao_path(@manutencao)
        else
          flash.now[:warning] = t('manutencaos.update.alerta')
          render :action => :edit
        end
      end
    end

    def destroy
      @manutencao = Manutencao.find params[:id]

      @manutencao.destroy
      flash[:notice] = t('manutencaos.destroy.sucesso')
      redirect_to casein_manutencaos_path
    end

    def filtro_relatorio
      # @manutencaos = apply_scopes(Manutencao).all

      # respond_to do |format|
      #   format.html
      #   format.pdf do
      #     render  template: "casein/manutencaos/imprimir_manutencao",
      #         handlers: [:erb],
      #         formats: [:pdf],
      #         page_size: "A3",
      #         pdf: "manutencao_#{Time.zone.now.to_s}",
      #         layout: 'layouts/pdf/pdf.html',
      #         header: {:html => {:template => 'layouts/pdf/header', handlers: [:erb], formats: [:pdf]}, :spacing => 8, :line => false},
      #         footer: {:html => {:template => 'layouts/pdf/footer', handlers: [:erb], formats: [:pdf]}, :line => false},
      #         margin: { :bottom => 20, :top => 35}
      #   end
      # end
    end

    def filtro_ajax
      @manutencaos = apply_scopes(Manutencao).order(sort_order(:poco_id))
    end

    def alerta_email_vendedor
      poco = Poco.find(params[:manutencao_id])
      manutencao = Manutencao.where(poco_id: poco.id).last
      vendedor = Casein::AdminUser.find(manutencao.vendedor_id) unless manutencao.blank?

      if vendedor.present?
        Mailer.alerta_email_vendedor(poco, vendedor).deliver
        flash[:notice] = t('manutencaos.alerta_email_vendedor.sucesso')
        redirect_to casein_dashboard_path
      else
        flash.now[:warning] = "t('manutencaos.alerta_email_vendedor.alerta')"
        redirect_to casein_dashboard_path
      end
    end

    private

      def manutencao_params
        params.require(:manutencao).permit(:poco_id, :servico_id, :numero_processo, :pessoa_contato, :telefone, :vendedor_id, :email,
          arquivos_attributes: [:id, :nome, :comentarios, :owner_id, :owner_type, :upload, :_destroy],
          manutencao_produtos_attributes: [:id, :produto_id, :quantidade, :observacao, :manutencao_id, :_destroy],
          manutencao_servicos_attributes: [:id, :tipo, :descricao, :data_servico, :manutencao_id, :_destroy,
          manutencao_funcionarios_attributes: [:id, :funcionario_id, :_destroy],
          manutencao_servico_itens_attributes: [:id, :produto_id, :quantidade, :_destroy],
        ]).tap do |whitelisted|
          whitelisted[:manutencao_checklists_attributes] = params[:manutencao][:manutencao_checklists_attributes]
        end
      end

  end
end