# Scaffolding generated by Casein v5.1.1.1

module Casein
  class ManutencaoProdutosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Manutencao produtos'
  		@manutencao_produtos = ManutencaoProduto.order(sort_order(:manutencao_id))
    end
  
    def show
      @casein_page_title = 'View manutencao produto'
      @manutencao_produto = ManutencaoProduto.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new manutencao produto'
    	@manutencao_produto = ManutencaoProduto.new
    end

    def create
      @manutencao_produto = ManutencaoProduto.new manutencao_produto_params
    
      if @manutencao_produto.save
        flash[:notice] = 'Manutencao produto created'
        redirect_to casein_manutencao_produtos_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new manutencao produto'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update manutencao produto'
      
      @manutencao_produto = ManutencaoProduto.find params[:id]
    
      if @manutencao_produto.update_attributes manutencao_produto_params
        flash[:notice] = 'Manutencao produto has been updated'
        redirect_to casein_manutencao_produtos_path
      else
        flash.now[:warning] = 'There were problems when trying to update this manutencao produto'
        render :action => :show
      end
    end
 
    def destroy
      @manutencao_produto = ManutencaoProduto.find params[:id]
      @manutencao = Manutencao.find(@manutencao_produto.manutencao_id)

      @manutencao_produto.destroy
      flash[:notice] = 'Manutencao produto has been deleted'
      respond_to do |format|
        format.html {redirect_to casein_manutencao_path(@manutencao)}
        format.js
      end
    end

    def cadastro_ajax
      @manutencao = Manutencao.find(params[:manutencao_id])
      @operacao_produto = ManutencaoProduto.create(produto_id: params[:produto_id], quantidade: params[:quantidade], observacao: params[:observacao], manutencao_id: @manutencao.id)
    end
  
    private
      
      def manutencao_produto_params
        params.require(:manutencao_produto).permit(:manutencao_id, :produto_id, :quantidade, :observacao)
      end

  end
end