# Scaffolding generated by Casein v5.1.1.1

module Casein
  class ManutencaoFuncionariosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Manutencao funcionarios'
  		@manutencao_funcionarios = ManutencaoFuncionario.order(sort_order(:manutencao_id))
    end
  
    def show
      @casein_page_title = 'View manutencao funcionario'
      @manutencao_funcionario = ManutencaoFuncionario.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new manutencao funcionario'
    	@manutencao_funcionario = ManutencaoFuncionario.new
    end

    def create
      @manutencao_funcionario = ManutencaoFuncionario.new manutencao_funcionario_params
    
      if @manutencao_funcionario.save
        flash[:notice] = 'Manutencao funcionario created'
        redirect_to casein_manutencao_funcionarios_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new manutencao funcionario'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update manutencao funcionario'
      
      @manutencao_funcionario = ManutencaoFuncionario.find params[:id]
    
      if @manutencao_funcionario.update_attributes manutencao_funcionario_params
        flash[:notice] = 'Manutencao funcionario has been updated'
        redirect_to casein_manutencao_funcionarios_path
      else
        flash.now[:warning] = 'There were problems when trying to update this manutencao funcionario'
        render :action => :show
      end
    end
 
    def destroy
      @manutencao_funcionario = ManutencaoFuncionario.find params[:id]

      @manutencao_funcionario.destroy
      flash[:notice] = 'Manutencao funcionario has been deleted'
      redirect_to casein_manutencao_funcionarios_path
    end
  
    private
      
      def manutencao_funcionario_params
        params.require(:manutencao_funcionario).permit(:manutencao_id, :funcionario_id)
      end

  end
end