# Scaffolding generated by Casein v5.1.1.1

module Casein
  class ManutencaoServicosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Manutencao servicos'
  		@manutencao_servicos = ManutencaoServico.order(sort_order(:manutencao_id))
    end
  
    def show
      @casein_page_title = 'View manutencao servico'
      @manutencao_servico = ManutencaoServico.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new manutencao servico'
    	@manutencao_servico = ManutencaoServico.new
    end

    def create
      @manutencao_servico = ManutencaoServico.new manutencao_servico_params
    
      if @manutencao_servico.save
        flash[:notice] = 'Manutencao servico created'
        redirect_to casein_manutencao_servicos_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new manutencao servico'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update manutencao servico'
      
      @manutencao_servico = ManutencaoServico.find params[:id]
    
      if @manutencao_servico.update_attributes manutencao_servico_params
        flash[:notice] = 'Manutencao servico has been updated'
        redirect_to casein_manutencao_servicos_path
      else
        flash.now[:warning] = 'There were problems when trying to update this manutencao servico'
        render :action => :show
      end
    end
 
    def destroy
      @manutencao_servico = ManutencaoServico.find params[:id]

      @manutencao_servico.destroy
      flash[:notice] = 'Manutencao servico has been deleted'
      redirect_to casein_manutencao_servicos_path
    end
  
    private
      
      def manutencao_servico_params
        params.require(:manutencao_servico).permit(:manutencao_id, :tipo, :descricao, :data_servico, manutencao_servico_itens_attributes: [:id, :produto_id, :quantidade, :_destroy])
      end

  end
end