# Scaffolding generated by Casein v5.1.1.1

module Casein
  class ManutencaoServicoItensController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Manutencao servico itens'
  		@manutencao_servico_itens = ManutencaoServicoItem.order(sort_order(:manutencao_servico_id))
    end
  
    def show
      @casein_page_title = 'View manutencao servico item'
      @manutencao_servico_item = ManutencaoServicoItem.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new manutencao servico item'
    	@manutencao_servico_item = ManutencaoServicoItem.new
    end

    def create
      @manutencao_servico_item = ManutencaoServicoItem.new manutencao_servico_item_params
    
      if @manutencao_servico_item.save
        flash[:notice] = 'Manutencao servico item created'
        redirect_to casein_manutencao_servico_itens_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new manutencao servico item'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update manutencao servico item'
      
      @manutencao_servico_item = ManutencaoServicoItem.find params[:id]
    
      if @manutencao_servico_item.update_attributes manutencao_servico_item_params
        flash[:notice] = 'Manutencao servico item has been updated'
        redirect_to casein_manutencao_servico_itens_path
      else
        flash.now[:warning] = 'There were problems when trying to update this manutencao servico item'
        render :action => :show
      end
    end
 
    def destroy
      @manutencao_servico_item = ManutencaoServicoItem.find params[:id]

      @manutencao_servico_item.destroy
      flash[:notice] = 'Manutencao servico item has been deleted'
      redirect_to casein_manutencao_servico_itens_path
    end
  
    private
      
      def manutencao_servico_item_params
        params.require(:manutencao_servico_item).permit(:manutencao_servico_id, :produto_id, :quantidade)
      end

  end
end