# Scaffolding generated by Casein v5.1.1.1

module Casein
  class MaquinasController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('maquinas.index.titulo')
  		@maquinas = Maquina.order(sort_order(:descricao))
    end

    def show
      @casein_page_title = t('maquinas.show.titulo')
      @maquina = Maquina.find params[:id]
    end

    def new
      @casein_page_title = t('maquinas.new.titulo')
    	@maquina = Maquina.new
    end

    def create
      @maquina = Maquina.new maquina_params

      if @maquina.save
        flash[:notice] = t('maquinas.create.sucesso', descricao: @maquina.descricao)
        redirect_to casein_maquinas_path
      else
        flash.now[:warning] = t('maquinas.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('maquinas.update.titulo')

      @maquina = Maquina.find params[:id]

      if @maquina.update_attributes maquina_params
        flash[:notice] = t('maquinas.update.sucesso', descricao: @maquina.descricao)
        redirect_to casein_maquinas_path
      else
        flash.now[:warning] = t('maquinas.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @maquina = Maquina.find params[:id]

      @maquina.destroy
      flash[:notice] = t('maquinas.destroy.sucesso')
      redirect_to casein_maquinas_path
    end
    
    def adicionar
      @maquina = Maquina.create(descricao: params[:item])
    end

    private

      def maquina_params
        params.require(:maquina).permit(:descricao)
      end

  end
end
