# Scaffolding generated by Casein v5.1.1.1

module Casein
  class MarcasController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = t('marcas.index.titulo')
  		@marcas = Marca.order(sort_order(:descricao))
    end
  
    def show
      @casein_page_title = t('marcas.show.titulo')
      @marca = Marca.find params[:id]
    end
  
    def new
      @casein_page_title = t('marcas.new.titulo')
    	@marca = Marca.new
    end

    def create
      @marca = Marca.new marca_params
    
      if @marca.save
        flash[:notice] = t('marcas.create.sucesso', descricao: @marca.descricao)
        redirect_to casein_marcas_path
      else
        flash.now[:warning] = t('marca.create.alerta')
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update marca'
      
      @marca = Marca.find params[:id]
    
      if @marca.update_attributes marca_params
        flash[:notice] = t('marcas.update.sucesso', descricao: @marca.descricao)
        redirect_to casein_marcas_path
      else
        flash.now[:warning] = t('marca.update.alerta')
        render :action => :show
      end
    end
 
    def destroy
      @marca = Marca.find params[:id]

      @marca.destroy
      flash[:notice] = t('marcas.destroy.sucesso')
      redirect_to casein_marcas_path
    end
  
    private
      
      def marca_params
        params.require(:marca).permit(:descricao)
      end

  end
end