# Scaffolding generated by Casein v5.1.1.1

module Casein
  class ModeloBombasController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('modelo_bombas.index.titulo')
  		@modelo_bombas = ModeloBomba.order(sort_order(:descricao))
    end

    def show
      @casein_page_title = t('modelo_bombas.show.titulo')
      @modelo_bomba = ModeloBomba.find params[:id]
    end

    def new
      @casein_page_title = t('modelo_bombas.new.titulo')
    	@modelo_bomba = ModeloBomba.new
    end

    def create
      @modelo_bomba = ModeloBomba.new modelo_bomba_params

      if @modelo_bomba.save
        flash[:notice] = t('modelo_bombas.create.sucesso', descricao: @modelo_bomba.descricao)
        redirect_to casein_modelo_bombas_path
      else
        flash.now[:warning] = t('modelo_bombas.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('modelo_bombas.update.titulo')

      @modelo_bomba = ModeloBomba.find params[:id]

      if @modelo_bomba.update_attributes modelo_bomba_params
        flash[:notice] = t('modelo_bombas.update.sucesso', descricao: @modelo_bomba.descricao)
        redirect_to casein_modelo_bombas_path
      else
        flash.now[:warning] = t('modelo_bombas.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @modelo_bomba = ModeloBomba.find params[:id]

      @modelo_bomba.destroy
      flash[:notice] = t('modelo_bombas.destroy.sucesso')
      redirect_to casein_modelo_bombas_path
    end

    def adicionar
      @modelo_bomba = ModeloBomba.create(descricao: params[:item])
      @target = "select_modelo_bomba"
    end

    private

      def modelo_bomba_params
        params.require(:modelo_bomba).permit(:descricao)
      end

  end
end
