# Scaffolding generated by Casein v5.1.1.1

module Casein
  class MotoresController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('motores.index.titulo')
  		@motores = Motor.order(sort_order(:descricao))
    end

    def show
      @casein_page_title = t('motores.show.titulo')
      @motor = Motor.find params[:id]
    end

    def new
      @casein_page_title = t('motores.new.titulo')
    	@motor = Motor.new
    end

    def create
      @motor = Motor.new motor_params

      if @motor.save
        flash[:notice] = t('motores.create.sucesso', descricao: @motor.descricao)
        redirect_to casein_motores_path
      else
        flash.now[:warning] = t('motores.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('motores.update.titulo')

      @motor = Motor.find params[:id]

      if @motor.update_attributes motor_params
        flash[:notice] = t('motores.update.sucesso', descricao: @motor.descricao)
        redirect_to casein_motores_path
      else
        flash.now[:warning] = t('motores.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @motor = Motor.find params[:id]

      @motor.destroy
      flash[:notice] = t('motores.destroy.sucesso')
      redirect_to casein_motores_path
    end

    def adicionar
      @motor = Motor.create(descricao: params[:item])
      @target = "select_motor"
    end

    private

      def motor_params
        params.require(:motor).permit(:descricao)
      end

  end
end
