# Scaffolding generated by Casein v5.1.1.1

module Casein
  class OrcamentosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
    has_scope :cliente_id
  
    def index
      @casein_page_title = t('orcamentos.index.titulo')
  		@orcamentos = Orcamento.order(sort_order(:cliente_id))
    end
  
    def show
      @casein_page_title = t('orcamentos.show.titulo')
      @orcamento = Orcamento.find params[:id]
    end
  
    def new
      @casein_page_title = t('orcamentos.new.titulo')
    	@orcamento = Orcamento.new
    end

    def create
      @orcamento = Orcamento.new orcamento_params
      @orcamento.casein_admin_user_id = @session_user.id
      if @orcamento.save
        flash[:notice] = t('orcamentos.create.sucesso', nome: @orcamento.cliente.pessoa.try(:nome))
        redirect_to casein_orcamento_path(@orcamento)
      else
        flash.now[:warning] = t('orcamentos.create.alerta')
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update orcamento'
      
      @orcamento = Orcamento.find params[:id]
      @orcamento.casein_admin_user_id = @session_user.id

      if @orcamento.update_attributes orcamento_params
        flash[:notice] = t('orcamentos.update.sucesso', nome: @orcamento.cliente.pessoa.try(:nome))
        redirect_to casein_orcamentos_path
      else
        flash.now[:warning] = t('orcamentos.update.alerta')
        render :action => :show
      end
    end
 
    def destroy
      @orcamento = Orcamento.find params[:id]

      @orcamento.destroy
      flash[:notice] = t('orcamentos.destroy.sucesso')
      redirect_to casein_orcamentos_path
    end
  
    def imprimir
      @orcamento = Orcamento.find params[:orcamento_id]
      respond_to do |format|
        format.html
        format.pdf do
          render  template: "casein/orcamentos/imprimir_orcamento",
              handlers: [:erb],
              formats: [:pdf],
              page_size: "A3",
              pdf: "orcamento_#{Time.zone.now.to_s}",
              layout: 'layouts/pdf/pdf.html.erb',
              header: {:html => {:template => 'layouts/pdf/header', handlers: [:erb], formats: [:pdf]}, :spacing => 8, :line => false},
              footer: {:html => {:template => 'layouts/pdf/footer', handlers: [:erb], formats: [:pdf]}, :line => false},
              margin: { :bottom => 20, :top => 35}
        end
      end
    end

    def filtro_ajax
      @orcamentos = apply_scopes(Orcamento).order(sort_order(:data_proposta))
    end

    private
      
      def orcamento_params
        params.require(:orcamento).permit(:cliente_id, :data_proposta, :casein_admin_user_id, :validade_proposta, :prazo_inicio, :prazo_execucao, :condicao_pagamento, :descricao, :cidade_data,
                                          orcamento_itens_attributes: [:id, :orcamento_id, :quantidade, :descricao, :preco_unitario, :preco_total, :_destroy])
      end

  end
end