# Scaffolding generated by Casein v5.1.1.1

module Casein
  class OrcamentoItensController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Orcamento itens'
  		@orcamento_itens = OrcamentoIten.order(sort_order(:orcamento_id))
    end
  
    def show
      @casein_page_title = 'View orcamento iten'
      @orcamento_iten = OrcamentoIten.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new orcamento iten'
    	@orcamento_iten = OrcamentoIten.new
    end

    def create
      @orcamento_iten = OrcamentoIten.new orcamento_iten_params
    
      if @orcamento_iten.save
        flash[:notice] = 'Orcamento iten created'
        redirect_to casein_orcamento_itens_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new orcamento iten'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update orcamento iten'
      
      @orcamento_iten = OrcamentoIten.find params[:id]
    
      if @orcamento_iten.update_attributes orcamento_iten_params
        flash[:notice] = 'Orcamento iten has been updated'
        redirect_to casein_orcamento_itens_path
      else
        flash.now[:warning] = 'There were problems when trying to update this orcamento iten'
        render :action => :show
      end
    end
 
    def destroy
      @orcamento_iten = OrcamentoIten.find params[:id]
      @orcamento = Orcamento.find(@orcamento_iten.orcamento_id)
      @orcamento_iten.destroy
      flash[:notice] = 'Item removido com sucesso!'
      respond_to do |format|
        format.html {redirect_to casein_orcamento_path(@orcamento)}
        format.js
      end
    end
  
    def cadastro_ajax
      @orcamento = Orcamento.find(params[:orcamento_id])
      @total = (params[:quantidade].to_f * params[:preco_unitario].gsub(",", ".").to_f)
      @orcamento_iten = OrcamentoIten.create(orcamento_id: params[:orcamento_id], quantidade: params[:quantidade], descricao: params[:descricao], preco_unitario: params[:preco_unitario], unidade: params[:unidade], preco_total: @total)
    end

    private
      
      def orcamento_iten_params
        params.require(:orcamento_iten).permit(:orcamento_id, :quantidade, :descricao, :preco_unitario, :preco_total, :unidade)
      end

  end
end