# Scaffolding generated by Casein v5.1.1.1

module Casein
  class OrdemServicosController < Casein::CaseinController
    load_and_authorize_resource

    def atualizar_status
      @manutencao = Manutencao.find(params[:manutencao_id])
      OrdemServico.find(@manutencao.ordem_servico_id).update(status: 5)

      respond_to do |format|
        flash[:notice] = 'Status Atualizado com Sucesso!'
        format.html { redirect_to casein_ordem_servicos_path }
      end
    end

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('ordem_servicos.index.titulo')
      @ordem_servicos = OrdemServico.order(id: :desc)
      @manutencaos = Manutencao.order(updated_at: :desc).joins(poco: [cliente: [:pessoa]]).joins(:manutencao_servicos).joins(:servico).joins("LEFT JOIN ordem_servicos on ordem_servicos.id = manutencaos.ordem_servico_id").where('ordem_servico_id is not null and ordem_servicos.status != 5').group('manutencaos.id')
    end

    def show
      @casein_page_title = t('ordem_servicos.show.titulo')
      @ordem_servico = OrdemServico.find params[:id]
      @manutencaos = Manutencao.where(ordem_servico_id: @ordem_servico.id)
    end

    def new
      @casein_page_title = t('ordem_servicos.new.titulo')
    	@ordem_servico = OrdemServico.new
    end

    def create
      @ordem_servico = OrdemServico.new ordem_servico_params
      @ordem_servico.status = 1

      if params[:nome] != ''
        pessoa = Pessoa.create(nome: params[:nome], email_contato: params[:email], telefone_principal: params[:telefone])
        pessoa.pessoas_contatos.create(nome_contato: params[:nome], email_contato: params[:email], telefone_contato: params[:telefone])
        cliente = Cliente.find_by(pessoa_id: pessoa.id)
        poco = Poco.create(cliente_id: cliente.id, poco_produtivo: params[:poco_produtivo], linha_endereco: params[:linha_endereco], apelido_endereco: params[:apelido_endereco], perfuracao_leao: params[:perfuracao_leao], cidade_id: params[:cidade_id], periodo_manutencao: params[:periodo_manutencao])
        @ordem_servico.poco_id = poco.id
      end

      if @ordem_servico.save
        handle_notification
        flash[:notice] = t('ordem_servicos.create.sucesso')
        redirect_to casein_ordem_servicos_path
      else
        flash.now[:warning] = t('ordem_servicos.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('clientes.update.titulo')

      @ordem_servico = OrdemServico.find params[:id]

      if ordem_servico_params[:status] == 'Finalização'
        if ordem_servico_params[:data_proxima_etapa] >= Time.current.strftime("%d/%m/%Y")
          if @ordem_servico.update_attributes ordem_servico_params
            if params[:periodo_manutencao_edit] != @ordem_servico.poco.periodo_manutencao
              @ordem_servico.poco.update(periodo_manutencao: params[:periodo_manutencao_edit])
            end
            handle_notification
            flash[:notice] = t('ordem_servicos.update.sucesso')
            redirect_to casein_ordem_servicos_path
          else
            flash.now[:warning] = t('ordem_servicos.update.alerta')
            render :action => :show
          end
        else
          flash.now[:warning] = 'Erro ao Salvar, data inválida!'
          render :action => :edit
        end
      else
        if @ordem_servico.update_attributes ordem_servico_params
          if params[:periodo_manutencao_edit] != @ordem_servico.poco.periodo_manutencao
            @ordem_servico.poco.update(periodo_manutencao: params[:periodo_manutencao_edit])
          end
          flash[:notice] = t('ordem_servicos.update.sucesso')
          redirect_to casein_ordem_servicos_path
        else
          flash.now[:warning] = t('ordem_servicos.update.alerta')
          render :action => :show
        end
      end
    end

    def destroy
      @ordem_servico = OrdemServico.find params[:id]

      @ordem_servico.destroy
      flash[:notice] = t('ordem_servicos.destroy.sucesso')
      redirect_to casein_ordem_servicos_path
    end

    private

      def ordem_servico_params
        params.require(:ordem_servico).permit(
          :observacoes, :abertura, :status, :funcionario_id, :poco_id, :sintoma, :data_servico_realizado, :data_proxima_etapa,
          :other_services,
          ordem_servico_servicos_attributes: [:id, :servico_id, :_destroy],
          ordem_servico_produtos_attributes: [:id, :produto_id, :_destroy, :qtd, :todo],
        )
      end

      def handle_notification
        @notification_user = UserApp.where(funcionarios_id: params['ordem_servico']['funcionario_id'])
        if params['ordem_servico']['data_proxima_etapa'].present?
          @t = Time.parse(params['ordem_servico']['data_proxima_etapa']) + 8*60*60 - 24*60*60
        end
        @time = @t && @t > Time.now ? @t : Time.now
        if @notification_user.present?
          params = {"app_id" => "900d59a2-af71-4319-88bf-124de5b5bcbf",
          "contents" => {"en" => "Uma nova ordem de serviço chegou, confira no aplicativo da Materiáguas."},
          "filters" => [{"field" => "tag", "key"=> "id", "relation"=> "=", "value" => @notification_user[0].id.to_s}],
          "send_after" => @time,
          "small_icon" => "icon",
        }
          uri = URI.parse('https://onesignal.com/api/v1/notifications')
          http = Net::HTTP.new(uri.host, uri.port)
          http.use_ssl = true

          # TODO: Trocar token de notificação

          request = Net::HTTP::Post.new(uri.path,
            'Content-Type'  => 'application/json;charset=utf-8',
            'Authorization' => "Basic ZjBlNWMyOTUtMWQwOC00OGQ3LTliN2ItMWQ2ZDYwNDM1NjY4")
          request.body = params.as_json.to_json
          response = http.request(request)
          puts response.body
      end

    end

  end
end