# Scaffolding generated by Casein v5.1.1.1

module Casein
  class PerfuracoesController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('perfuracoes.index.titulo')
  		@perfuracoes = Perfuracao.order(sort_order(:poco_id))
    end

    def show
      @casein_page_title = t('perfuracoes.show.titulo')
      @perfuracao = Perfuracao.find params[:id]
      @perfuracao.perfuracao_funcionarios.build
      
    end

    def new
      @casein_page_title = t('perfuracoes.new.titulo')
    	@perfuracao = Perfuracao.new
      @perfuracao.perfuracao_funcionarios.build

    end

    def create
      @perfuracao = Perfuracao.new perfuracao_params

      if @perfuracao.save
        flash[:notice] = t('perfuracoes.create.sucesso', data_perfuracao_inicio: @perfuracao.data_perfuracao_inicio)
        redirect_to casein_perfuracoes_path
      else
        flash.now[:warning] = t('perfuracoes.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('perfuracoes.update.titulo')

      @perfuracao = Perfuracao.find params[:id]

      if @perfuracao.update_attributes perfuracao_params
        flash[:notice] = t('perfuracoes.update.sucesso', data_perfuracao_inicio: @perfuracao.data_perfuracao_inicio)
        redirect_to casein_perfuracoes_path
      else
        flash.now[:warning] = t('perfuracoes.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @perfuracao = Perfuracao.find params[:id]

      @perfuracao.destroy
      flash[:notice] = t('perfuracoes.destroy.sucesso')
      redirect_to casein_perfuracoes_path
    end

    private

      def perfuracao_params
        params.require(:perfuracao).permit(:poco_id, :data_perfuracao_inicio, :data_perfuracao_fim, :profundidade, :maquina_id, :bitola_id,
                                            perfuracao_funcionarios_attributes: [:id, :perfuracao_id, :funcionario_id])
      end
  end
end
