# Scaffolding generated by Casein v5.1.1.1

module Casein
  class PerfuracaoFuncionariosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Perfuracao funcionarios'
  		@perfuracao_funcionarios = PerfuracaoFuncionario.order(sort_order(:perfuracao_id))
    end
  
    def show
      @casein_page_title = 'View perfuracao funcionario'
      @perfuracao_funcionario = PerfuracaoFuncionario.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new perfuracao funcionario'
    	@perfuracao_funcionario = PerfuracaoFuncionario.new
    end

    def create
      @perfuracao_funcionario = PerfuracaoFuncionario.new perfuracao_funcionario_params
    
      if @perfuracao_funcionario.save
        flash[:notice] = 'Perfuracao funcionario created'
        redirect_to casein_perfuracao_funcionarios_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new perfuracao funcionario'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update perfuracao funcionario'
      
      @perfuracao_funcionario = PerfuracaoFuncionario.find params[:id]
    
      if @perfuracao_funcionario.update_attributes perfuracao_funcionario_params
        flash[:notice] = 'Perfuracao funcionario has been updated'
        redirect_to casein_perfuracao_funcionarios_path
      else
        flash.now[:warning] = 'There were problems when trying to update this perfuracao funcionario'
        render :action => :show
      end
    end
 
    def destroy
      @perfuracao_funcionario = PerfuracaoFuncionario.find params[:id]

      @perfuracao_funcionario.destroy
      flash[:notice] = 'Perfuracao funcionario has been deleted'
      redirect_to casein_perfuracao_funcionarios_path
    end
  
    private
      
      def perfuracao_funcionario_params
        params.require(:perfuracao_funcionario).permit(:perfuracao_id, :funcionario_id)
      end

  end
end