# Scaffolding generated by Casein v5.1.0.0

module Casein
  class PessoasFisicasController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def show
      @casein_page_title = 'View pessoa fisica'
      @pessoa_fisica = PessoaFisica.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new pessoa fisica'
    	@pessoa_fisica = PessoaFisica.new
    end

    def create
      @pessoa_fisica = PessoaFisica.new pessoa_fisica_params

      if @pessoa_fisica.save
        flash[:notice] = 'Pessoa fisica created'
        redirect_to casein_pessoas_fisicas_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new pessoa fisica'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update pessoa fisica'

      @pessoa_fisica = PessoaFisica.find params[:id]

      if @pessoa_fisica.update_attributes pessoa_fisica_params
        flash[:notice] = 'Pessoa fisica has been updated'
        redirect_to casein_pessoas_fisicas_path
      else
        flash.now[:warning] = 'There were problems when trying to update this pessoa fisica'
        render :action => :show
      end
    end

    def destroy
      @pessoa_fisica = PessoaFisica.find params[:id]

      @pessoa_fisica.destroy
      flash[:notice] = 'Pessoa fisica has been deleted'
      redirect_to casein_pessoas_fisicas_path
    end

    private

      def pessoa_fisica_params
        params.require(:pessoa_fisica).permit(:cpf, :rg, :data_nascimento, :estado_civil, :sexo, :pessoa)
      end

  end
end
