# Scaffolding generated by Casein v5.1.0.0

module Casein
  class PessoasEnderecosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def show
      @casein_page_title = 'View pessoa endereco'
      @pessoa_endereco = PessoaEndereco.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new pessoa endereco'
    	@pessoa_endereco = PessoaEndereco.new
    end

    def create
      @pessoa_endereco = PessoaEndereco.new pessoa_endereco_params
    
      if @pessoa_endereco.save
        flash[:notice] = 'Pessoa endereco created'
        redirect_to casein_pessoas_enderecos_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new pessoa endereco'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update pessoa endereco'
      
      @pessoa_endereco = PessoaEndereco.find params[:id]
    
      if @pessoa_endereco.update_attributes pessoa_endereco_params
        flash[:notice] = 'Pessoa endereco has been updated'
        redirect_to casein_pessoas_enderecos_path
      else
        flash.now[:warning] = 'There were problems when trying to update this pessoa endereco'
        render :action => :show
      end
    end
 
    def destroy
      @pessoa_endereco = PessoaEndereco.find params[:id]

      @pessoa_endereco.destroy
      flash[:notice] = 'Pessoa endereco has been deleted'
      redirect_to casein_pessoas_enderecos_path
    end
  
    private
      
      def pessoa_endereco_params
        params.require(:pessoa_endereco).permit(:tipo_endereco, :cep, :endereco, :numero, :complemento, :bairro, :cidade_id, :cidade_natal_id, :pessoa)
      end

  end
end