# Scaffolding generated by Casein v5.1.0.0

module Casein
  class PessoasController < Casein::CaseinController
    load_and_authorize_resource
    
    has_scope :nome
    has_scope :tipo
    has_scope :cpf
    has_scope :cnpj
    # has_scope :casein_admin_user

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('pessoas.index.titulo')

      if params[:nome] #deixei só um porque o nome sempre vai vir na busca
        @pessoas = apply_scopes(Pessoa).order(:nome)
      elsif params[:cpf] #valida se esta buscando pelo CPF
        @valida = Pessoa.select("*").joins(:pessoa_fisica).where(pessoas_fisicas: {cpf: params[:cpf]}).where.not(id: params[:id]).first
      elsif params[:cnpj] #valida se esta buscando pelo CNPJ
        @valida = Pessoa.select("*").joins(:pessoa_juridica).where(pessoas_juridicas: {cnpj: params[:cnpj]}).where.not(id: params[:id]).first
      else
        @pessoas = Pessoa.order(:nome)
      end

      respond_to do |format|
        format.html
        format.js
      end
    end

    def show
      @casein_page_title = t('pessoas.show.titulo')
      @pessoa = Pessoa.find params[:id]
    end

    def edit
      # @casein_page_title = t('pessoas.edit.titulo')
      @pessoa = Pessoa.find params[:id]
      @pessoa.build_pessoa_fisica unless @pessoa.pessoa_fisica
      @pessoa.build_pessoa_juridica unless @pessoa.pessoa_juridica
      @pessoa.build_pessoa_endereco unless @pessoa.pessoa_endereco
      @pessoa.pessoas_contatos.build
    end

    def new
      @casein_page_title = t('servicos.new.titulo')
    	@pessoa = Pessoa.new(tipo: false)
      @pessoa.build_pessoa_fisica
      @pessoa.build_pessoa_juridica
      @pessoa.build_pessoa_endereco
      @pessoa.pessoas_contatos.build
    end

    def create
      @pessoa = Pessoa.new pessoa_params

      if @pessoa.save
        flash[:notice] = t('pessoas.create.sucesso', nome: @pessoa.nome)
        redirect_to casein_pessoa_url(@pessoa)
      else
        @pessoa.build_pessoa_fisica unless @pessoa.pessoa_fisica
        @pessoa.build_pessoa_juridica unless @pessoa.pessoa_juridica
        @pessoa.build_pessoa_endereco unless @pessoa.pessoa_endereco

        flash.now[:warning] = t('pessoas.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update pessoa'

      @pessoa = Pessoa.find params[:id]

      if @pessoa.update_attributes pessoa_params
        flash[:notice] = t('pessoas.update.sucesso', nome: @pessoa.nome)
        redirect_to casein_pessoa_url(@pessoa)
      else
        @pessoa.build_pessoa_fisica unless @pessoa.pessoa_fisica
        @pessoa.build_pessoa_juridica unless @pessoa.pessoa_juridica
        @pessoa.build_pessoa_endereco unless @pessoa.pessoa_endereco

        flash.now[:warning] = t('pessoas.update.alerta')
        render :action => :edit
      end
    end

    def destroy
      @pessoa = Pessoa.find params[:id]
      @pessoa.destroy

      #fazer validação para nao deixar apagar caso tenha alguma amarração

      flash[:notice] = t('pessoas.destroy.sucesso')
      redirect_to casein_clientes_url
    end

    def filtro_ajax
      if params[:nome] #deixei só um porque o nome sempre vai vir na busca
        @pessoas = apply_scopes(Pessoa).group(:id).order(sort_order(:nome))
      end
    end

    def aniversariantes
      params[:mes] = Date.today.month unless params[:mes].present?

      @pessoas = Pessoa.find_by_sql("SELECT pessoas.nome, pessoas.email_contato, pessoas_fisicas.data_nascimento FROM pessoas INNER JOIN pessoas_fisicas ON pessoas_fisicas.pessoa_id = pessoas.id WHERE (pessoas_fisicas.data_nascimento IS NOT NULL AND MONTH(pessoas_fisicas.data_nascimento) = '#{params[:mes]}') UNION ALL SELECT pessoas_contatos.nome_contato as nome, pessoas_contatos.email_contato, pessoas_contatos.data_nascimento_contato as data_nascimento FROM pessoas_contatos WHERE pessoas_contatos.data_nascimento_contato IS NOT NULL AND MONTH(pessoas_contatos.data_nascimento_contato) = '#{params[:mes]}' ORDER BY data_nascimento, nome ASC")
    end

    private

      def pessoa_params
        params.require(:pessoa).permit(:nome, :tipo, :email_contato, :email_xml, :telefone_principal, pessoa_fisica_attributes: [:id, :cpf, :rg, :data_nascimento, :telefone_auxiliar_1, :telefone_auxiliar_2, :telefone_auxiliar_3], pessoa_juridica_attributes: [:id, :nome_fantasia, :cnpj, :ie, :im, :data_fundacao], pessoa_endereco_attributes: [:id, :tipo_endereco, :cep, :endereco, :numero, :complemento, :bairro, :cidade_id, :cidade_natal_id], pessoas_contatos_attributes: [:id, :nome_contato, :email_contato, :data_nascimento_contato, :telefone_contato, :_destroy])
      end

  end
end