# Scaffolding generated by Casein v5.1.0.0

module Casein
  class PessoasJuridicasController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def show
      @casein_page_title = 'View pessoa juridica'
      @pessoa_juridica = PessoaJuridica.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new pessoa juridica'
    	@pessoa_juridica = PessoaJuridica.new
    end

    def create
      @pessoa_juridica = PessoaJuridica.new pessoa_juridica_params
    
      if @pessoa_juridica.save
        flash[:notice] = 'Pessoa juridica created'
        redirect_to casein_pessoas_juridicas_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new pessoa juridica'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update pessoa juridica'
      
      @pessoa_juridica = PessoaJuridica.find params[:id]
    
      if @pessoa_juridica.update_attributes pessoa_juridica_params
        flash[:notice] = 'Pessoa juridica has been updated'
        redirect_to casein_pessoas_juridicas_path
      else
        flash.now[:warning] = 'There were problems when trying to update this pessoa juridica'
        render :action => :show
      end
    end
 
    def destroy
      @pessoa_juridica = PessoaJuridica.find params[:id]

      @pessoa_juridica.destroy
      flash[:notice] = 'Pessoa juridica has been deleted'
      redirect_to casein_pessoas_juridicas_path
    end
  
    private
      
      def pessoa_juridica_params
        params.require(:pessoa_juridica).permit(:nome_fantasia, :cnpj, :ie, :im, :data_fundacao, :pessoa)
      end

  end
end