# Scaffolding generated by Casein v5.1.0.0

module Casein
  class PessoasContatosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def show
      @casein_page_title = 'View pessoa contato'
      @pessoa_contato = PessoaContato.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new pessoa contato'
    	@pessoa_contato = PessoaContato.new
    end

    def create
      @pessoa_contato = PessoaContato.new pessoa_contato_params
    
      if @pessoa_contato.save
        flash[:notice] = 'Pessoa contato created'
        redirect_to casein_pessoas_contatos_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new pessoa contato'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update pessoa contato'
      
      @pessoa_contato = PessoaContato.find params[:id]
    
      if @pessoa_contato.update_attributes pessoa_contato_params
        flash[:notice] = 'Pessoa contato has been updated'
        redirect_to casein_pessoas_contatos_path
      else
        flash.now[:warning] = 'There were problems when trying to update this pessoa contato'
        render :action => :show
      end
    end
 
    def destroy
      @pessoa_contato = PessoaContato.find params[:id]

      @pessoa_contato.destroy
      flash[:notice] = 'Pessoa contato has been deleted'
      redirect_to casein_pessoas_contatos_path
    end
  
    private
      
      def pessoa_contato_params
        params.require(:pessoa_contato).permit(:tipo_contato, :valor, :pessoa)
      end

  end
end