# Scaffolding generated by Casein v5.1.0.0

module Casein
  class PessoasDadosBancariosController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def show
      @casein_page_title = 'View pessoa dado bancario'
      @pessoa_dado_bancario = PessoaDadoBancario.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new pessoa dado bancario'
    	@pessoa_dado_bancario = PessoaDadoBancario.new
    end

    def create
      @pessoa_dado_bancario = PessoaDadoBancario.new pessoa_dado_bancario_params

      if @pessoa_dado_bancario.save
        flash[:notice] = 'Pessoa dado bancario created'
        redirect_to casein_pessoas_dados_bancarios_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new pessoa dado bancario'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update pessoa dado bancario'

      @pessoa_dado_bancario = PessoaDadoBancario.find params[:id]

      if @pessoa_dado_bancario.update_attributes pessoa_dado_bancario_params
        flash[:notice] = 'Pessoa dado bancario has been updated'
        redirect_to casein_pessoas_dados_bancarios_path
      else
        flash.now[:warning] = 'There were problems when trying to update this pessoa dado bancario'
        render :action => :show
      end
    end

    def destroy
      @pessoa_dado_bancario = PessoaDadoBancario.find params[:id]

      @pessoa_dado_bancario.destroy
      flash[:notice] = 'Pessoa dado bancario has been deleted'
      redirect_to casein_pessoas_dados_bancarios_path
    end

    private

      def pessoa_dado_bancario_params
        params.require(:pessoa_dado_bancario).permit(:nome_banco, :agencia, :conta, :pessoa)
      end

  end
end
