# Scaffolding generated by Casein v5.1.0.0

module Casein
  class PessoasClassificacoesController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def show
      @casein_page_title = 'View pessoa classificacao'
      @pessoa_classificacao = PessoaClassificacao.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new pessoa classificacao'
    	@pessoa_classificacao = PessoaClassificacao.new
    end

    def create
      @pessoa_classificacao = PessoaClassificacao.new pessoa_classificacao_params
    
      if @pessoa_classificacao.save
        flash[:notice] = 'Pessoa classificacao created'
        redirect_to casein_pessoas_classificacoes_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new pessoa classificacao'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update pessoa classificacao'
      
      @pessoa_classificacao = PessoaClassificacao.find params[:id]
    
      if @pessoa_classificacao.update_attributes pessoa_classificacao_params
        flash[:notice] = 'Pessoa classificacao has been updated'
        redirect_to casein_pessoas_classificacoes_path
      else
        flash.now[:warning] = 'There were problems when trying to update this pessoa classificacao'
        render :action => :show
      end
    end
 
    def destroy
      @pessoa_classificacao = PessoaClassificacao.find params[:id]

      @pessoa_classificacao.destroy
      flash[:notice] = 'Pessoa classificacao has been deleted'
      redirect_to casein_pessoas_classificacoes_path
    end
  
    private
      
      def pessoa_classificacao_params
        params.require(:pessoa_classificacao).permit(:classificacao, :pessoa)
      end

  end
end