# Scaffolding generated by Casein v5.1.1.1

module Casein
  class PosVendasController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
    has_scope :cliente_id
  
    def index
      @casein_page_title = t('pos_vendas.index.titulo')
  		@pos_vendas = PosVenda.order(sort_order(:resposta1))
    end
  
    def show
      @casein_page_title = t('pos_vendas.show.titulo')
      @pos_venda = PosVenda.find params[:id]
    end
  
    def new
      @casein_page_title = t('pos_vendas.new.titulo')
    	@pos_venda = PosVenda.new
    end

    def create
      @pos_venda = PosVenda.new pos_venda_params
    
      if @pos_venda.save

        if @pos_venda.resposta3 == 1
          @res3 = "Sim"
        else
          @res3 = "Nao"
        end

        if @pos_venda.resposta6 == 1
          @res6 = "Sim"
        else
          @res6 = "Nao"
        end

        @resposta1 = "#{@pos_venda.resposta1}, " + "Qual: #{params[:resposta1_qual]}"
        @resposta2 = "#{@pos_venda.resposta2}, " + "#{params[:resposta2_observacao]}"
        @resposta3 = "#{@res3}, " + "Porque: #{params[:resposta3_porque]}"
        @resposta6 = "#{@res6}, " + "Porque: #{params[:resposta6_porque]}. " + "Contato: #{params[:resposta6_contato]}, " + "Telefone: #{params[:resposta6_telefone]}"
        
        @pos_venda.update_attributes(resposta1: @resposta1, resposta2: @resposta2, resposta3: @resposta3, resposta6: @resposta6)
        
        flash[:notice] = t('pos_vendas.create.sucesso', id: @pos_venda.cliente_id)
        redirect_to casein_pos_vendas_path
      else
        flash.now[:warning] = t('pos_vendas.create.alerta')
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update pos venda'
      @pos_venda = PosVenda.find params[:id]

      if @pos_venda.update_attributes pos_venda_params
        
        if @pos_venda.resposta3 == 1
          @res3 = "Sim"
        else
          @res3 = "Nao"
        end

        if @pos_venda.resposta6 == 1
          @res6 = "Sim"
        else
          @res6 = "Nao"
        end

        @resposta1 = "#{@pos_venda.resposta1}, " + "Qual: #{params[:resposta1_qual]}"
        @resposta2 = "#{@pos_venda.resposta2}, " + "#{params[:resposta2_observacao]}"
        @resposta3 = "#{@res3}, " + "Porque: #{params[:resposta3_porque]}"
        @resposta6 = "#{@res6}, " + "Porque: #{params[:resposta6_porque]}. " + "Contato: #{params[:resposta6_contato]}, " + "Telefone: #{params[:resposta6_telefone]}"
        
        @pos_venda.update_attributes(resposta1: @resposta1, resposta2: @resposta2, resposta3: @resposta3, resposta6: @resposta6)
        
        flash[:notice] = t('pos_vendas.update.sucesso', id: @pos_venda.cliente_id)
        redirect_to casein_pos_vendas_path
      else
        flash.now[:warning] = t('pos_vendas.update.alerta')
        render :action => :show
      end
    end
 
    def destroy
      @pos_venda = PosVenda.find params[:id]

      @pos_venda.destroy
      flash[:notice] = t('pos_vendas.destroy.sucesso')
      redirect_to casein_pos_vendas_path
    end

    def filtro_ajax
      @pos_vendas = apply_scopes(PosVenda).order(sort_order(:cliente_id))
    end
  
    private
      
      def pos_venda_params
        params.require(:pos_venda).permit(:resposta1, :resposta2, :resposta3, :resposta4, :resposta5, :resposta6, :resposta7, :resposta8, :resposta9, :resposta10, :cliente_id)
      end

  end
end