# Scaffolding generated by Casein v5.1.1.1

module Casein
  class ProdutosController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('produtos.index.titulo')
  		@produtos = Produto.order(sort_order(:descricao))
    end

    def show
      @casein_page_title = t('produtos.show.titulo')
      @produto = Produto.find params[:id]
    end

    def new
      @casein_page_title = t('produtos.new.titulo')
    	@produto = Produto.new
    end

    def create
      @produto = Produto.new produto_params

      if @produto.save
        flash[:notice] = t('produtos.create.sucesso', descricao: @produto.descricao)
        redirect_to casein_produtos_path
      else
        flash.now[:warning] = t('produtos.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update produto'

      @produto = Produto.find params[:id]

      if @produto.update_attributes produto_params
        flash[:notice] = t('produtos.update.sucesso', descricao: @produto.descricao)
        redirect_to casein_produtos_path
      else
        flash.now[:warning] = t('produtos.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @produto = Produto.find params[:id]

      @produto.destroy
      flash[:notice] = t('produtos.destroy.sucesso')
      redirect_to casein_produtos_path
    end

    def adicionar
      @produto = Produto.create(descricao: params[:item], unidade_medida_id: 1)
      @target = "select_produto_#{params[:index]}"
    end

    private

      def produto_params
        params.require(:produto).permit(:descricao, :marca_id, :unidade_medida_id, :exibir_app)
      end

  end
end