# Scaffolding generated by Casein v5.1.1.1

module Casein
  class RelatoriosController < Casein::CaseinController
    before_filter :needs_admin_or_current_user
  
    def graficos_pos_vendas
      @relatorio_dados = PerfuracaoPosvenda.all
    end
  
    def sugestoes_pos_vendas
      @sugestoes = PerfuracaoPosvenda.find_by_sql("SELECT id, '0' as tipo, pergunta9 as descricao, created_at
                                                   FROM perfuracao_posvendas
                                                   UNION ALL
                                                   SELECT id, '1' as tipo, pergunta10 as descricao, created_at
                                                   FROM assistencia_posvendas
                                                   ORDER BY created_at DESC")
    end
  
  end
end