# Scaffolding generated by Casein v5.1.1.1

module Casein
  class RevestimentoPocosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Revestimento pocos'
  		@revestimento_pocos = RevestimentoPoco.order(sort_order(:quantidade))
    end
  
    def show
      @casein_page_title = 'View revestimento poco'
      @revestimento_poco = RevestimentoPoco.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new revestimento poco'
    	@revestimento_poco = RevestimentoPoco.new
    end

    def create
      @revestimento_poco = RevestimentoPoco.new revestimento_poco_params
    
      if @revestimento_poco.save
        flash[:notice] = 'Revestimento poco created'
        redirect_to casein_revestimento_pocos_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new revestimento poco'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update revestimento poco'
      
      @revestimento_poco = RevestimentoPoco.find params[:id]
    
      if @revestimento_poco.update_attributes revestimento_poco_params
        flash[:notice] = 'Revestimento poco has been updated'
        redirect_to casein_revestimento_pocos_path
      else
        flash.now[:warning] = 'There were problems when trying to update this revestimento poco'
        render :action => :show
      end
    end
 
    def destroy
      @revestimento_poco = RevestimentoPoco.find params[:id]

      @revestimento_poco.destroy
      flash[:notice] = 'Revestimento poco has been deleted'
      redirect_to casein_revestimento_pocos_path
    end
  
    private
      
      def revestimento_poco_params
        params.require(:revestimento_poco).permit(:quantidade, :tipo_revestimento_id, :poco_id, :polegadas)
      end

  end
end