# Scaffolding generated by Casein v5.1.1.1

module Casein
  class RevestimentoPocosBitolaController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = 'Revestimento pocos bitola'
  		@revestimento_pocos_bitola = RevestimentoPocoBitola.order(sort_order(:revestimento_poco_id))
    end

    def show
      @casein_page_title = 'View revestimento poco bitola'
      @revestimento_poco_bitola = RevestimentoPocoBitola.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new revestimento poco bitola'
    	@revestimento_poco_bitola = RevestimentoPocoBitola.new
    end

    def create
      @revestimento_poco_bitola = RevestimentoPocoBitola.new revestimento_poco_bitola_params

      if @revestimento_poco_bitola.save
        flash[:notice] = 'Revestimento poco bitola created'
        redirect_to casein_revestimento_pocos_bitola_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new revestimento poco bitola'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update revestimento poco bitola'

      @revestimento_poco_bitola = RevestimentoPocoBitola.find params[:id]

      if @revestimento_poco_bitola.update_attributes revestimento_poco_bitola_params
        flash[:notice] = 'Revestimento poco bitola has been updated'
        redirect_to casein_revestimento_pocos_bitola_path
      else
        flash.now[:warning] = 'There were problems when trying to update this revestimento poco bitola'
        render :action => :show
      end
    end

    def destroy
      @revestimento_poco_bitola = RevestimentoPocoBitola.find params[:id]

      @revestimento_poco_bitola.destroy
      flash[:notice] = 'Revestimento poco bitola has been deleted'
      redirect_to casein_revestimento_pocos_bitola_path
    end

    private

      def revestimento_poco_bitola_params
        params.require(:revestimento_poco_bitola).permit(:revestimento_poco_id, :bitola_id)
      end

  end
end
