# Scaffolding generated by Casein v5.1.1.1

module Casein
  class ServicosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = t('servicos.index.titulo')
  		@servicos = Servico.order(sort_order(:descricao))
    end
  
    def show
      @casein_page_title = t('servicos.update.titulo')
      @servico = Servico.find params[:id]
    end
  
    def new
      @casein_page_title = t('servicos.new.titulo')
    	@servico = Servico.new
    end

    def create
      @servico = Servico.new servico_params
    
      if @servico.save
        flash[:notice] = t('servicos.create.sucesso', descricao: @servico.descricao)
        redirect_to casein_servicos_path
      else
        flash.now[:warning] = t('servicos.create.alerta')
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update servico'
      
      @servico = Servico.find params[:id]
    
      if @servico.update_attributes servico_params
        flash[:notice] = t('servicos.update.sucesso', descricao: @servico.descricao)
        redirect_to casein_servicos_path
      else
        flash.now[:warning] = t('servicos.update.alerta')
        render :action => :show
      end
    end
 
    def destroy
      @servico = Servico.find params[:id]

      @servico.destroy
      flash[:notice] = t('servicos.destroy.sucesso')
      redirect_to casein_servicos_path
    end
  
    private
      
      def servico_params
        params.require(:servico).permit(:descricao)
      end

  end
end