# Scaffolding generated by Casein v5.1.1.1

module Casein
  class TipoRevestimentosController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = t('tipo_revestimentos.index.titulo')
  		@tipo_revestimentos = TipoRevestimento.order(sort_order(:descricao))
    end

    def show
      @casein_page_title = t('tipo_revestimentos.show.titulo')
      @tipo_revestimento = TipoRevestimento.find params[:id]
    end

    def new
      @casein_page_title = t('tipo_revestimentos.new.titulo')
    	@tipo_revestimento = TipoRevestimento.new
    end

    def create
      @tipo_revestimento = TipoRevestimento.new tipo_revestimento_params

      if @tipo_revestimento.save
        flash[:notice] = t('tipo_revestimentos.create.sucesso', descricao: @tipo_revestimento.descricao)
        redirect_to casein_tipo_revestimentos_path
      else
        flash.now[:warning] = t('tipo_revestimentos.create.alerta')
        render :action => :new
      end
    end

    def update
      @casein_page_title = t('tipo_revestimentos.update.titulo')

      @tipo_revestimento = TipoRevestimento.find params[:id]

      if @tipo_revestimento.update_attributes tipo_revestimento_params
        flash[:notice] = t('tipo_revestimentos.update.sucesso', descricao: @tipo_revestimento.descricao)
        redirect_to casein_tipo_revestimentos_path
      else
        flash.now[:warning] = t('tipo_revestimentos.update.alerta')
        render :action => :show
      end
    end

    def destroy
      @tipo_revestimento = TipoRevestimento.find params[:id]

      @tipo_revestimento.destroy
      flash[:notice] = t('tipo_revestimentos.destroy.sucesso')
      redirect_to casein_tipo_revestimentos_path
    end

    private

      def tipo_revestimento_params
        params.require(:tipo_revestimento).permit(:descricao)
      end

  end
end
