# Scaffolding generated by Casein v5.1.1.1

module Casein
  class UnidadesMedidasController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = t('unidades_medidas.index.titulo')
  		@unidades_medidas = UnidadeMedida.order(sort_order(:descricao))
    end
  
    def show
      @casein_page_title = t('unidades_medidas.show.titulo')
      @unidade_medida = UnidadeMedida.find params[:id]
    end
  
    def new
      @casein_page_title = t('unidades_medidas.new.titulo')
    	@unidade_medida = UnidadeMedida.new
    end

    def create
      @unidade_medida = UnidadeMedida.new unidade_medida_params
    
      if @unidade_medida.save
        flash[:notice] = t('unidades_medidas.create.sucesso', descricao: @unidade_medida.descricao)
        redirect_to casein_unidades_medidas_path
      else
        flash.now[:warning] = t('unidades_medidas.create.alerta')
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update unidade medida'
      
      @unidade_medida = UnidadeMedida.find params[:id]
    
      if @unidade_medida.update_attributes unidade_medida_params
        flash[:notice] = t('unidades_medidas.update.sucesso', descricao: @unidade_medida.descricao)
        redirect_to casein_unidades_medidas_path
      else
        flash.now[:warning] = t('unidades_medidas.update.alerta')
        render :action => :show
      end
    end
 
    def destroy
      @unidade_medida = UnidadeMedida.find params[:id]

      @unidade_medida.destroy
      flash[:notice] = t('unidades_medidas.destroy.sucesso')
      redirect_to casein_unidades_medidas_path
    end
  
    private
      
      def unidade_medida_params
        params.require(:unidade_medida).permit(:descricao)
      end

  end
end