# Scaffolding generated by Casein v5.1.1.1

module Casein
  class UsuarioCidadesController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Usuario cidades'
  		@usuario_cidades = UsuarioCidade.order(sort_order(:cidade_id))
    end
  
    def show
      @casein_page_title = 'View usuario cidade'
      @usuario_cidade = UsuarioCidade.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new usuario cidade'
    	@usuario_cidade = UsuarioCidade.new
    end

    def create
      @usuario_cidade = UsuarioCidade.new usuario_cidade_params
    
      if @usuario_cidade.save
        flash[:notice] = 'Usuario cidade created'
        redirect_to casein_usuario_cidades_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new usuario cidade'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update usuario cidade'
      
      @usuario_cidade = UsuarioCidade.find params[:id]
    
      if @usuario_cidade.update_attributes usuario_cidade_params
        flash[:notice] = 'Usuario cidade has been updated'
        redirect_to casein_usuario_cidades_path
      else
        flash.now[:warning] = 'There were problems when trying to update this usuario cidade'
        render :action => :show
      end
    end
 
    def destroy
      @usuario_cidade = UsuarioCidade.find params[:id]
      @user = Casein::AdminUser.find(@usuario_cidade.admin_user_id)

      @usuario_cidade.destroy
      flash[:notice] = 'Cidade removido desse usuario com sucesso!'
    end

    def cadastro_ajax
      @user = Casein::AdminUser.find(params[:admin_user_id])
      unless params[:cidade_id].blank?
        UsuarioCidade.create(admin_user_id: @user.id, cidade_id: params[:cidade_id]) 
      else 
        @erro = "Erro! Preencha os campos de estado e cidade para adicionar."
      end
    end
  
    private
      
      def usuario_cidade_params
        params.require(:usuario_cidade).permit(:cidade_id, :admin_user_id)
      end

  end
end