# Scaffolding generated by Casein v5.1.1.1

module Casein
  class VazaoAguaFuncionariosController < Casein::CaseinController
    load_and_authorize_resource
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Vazao agua funcionarios'
  		@vazao_agua_funcionarios = VazaoAguaFuncionario.order(sort_order(:vazao_agua_id))
    end
  
    def show
      @casein_page_title = 'View vazao agua funcionario'
      @vazao_agua_funcionario = VazaoAguaFuncionario.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new vazao agua funcionario'
    	@vazao_agua_funcionario = VazaoAguaFuncionario.new
    end

    def create
      @vazao_agua_funcionario = VazaoAguaFuncionario.new vazao_agua_funcionario_params
    
      if @vazao_agua_funcionario.save
        flash[:notice] = 'Vazao agua funcionario created'
        redirect_to casein_vazao_agua_funcionarios_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new vazao agua funcionario'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update vazao agua funcionario'
      
      @vazao_agua_funcionario = VazaoAguaFuncionario.find params[:id]
    
      if @vazao_agua_funcionario.update_attributes vazao_agua_funcionario_params
        flash[:notice] = 'Vazao agua funcionario has been updated'
        redirect_to casein_vazao_agua_funcionarios_path
      else
        flash.now[:warning] = 'There were problems when trying to update this vazao agua funcionario'
        render :action => :show
      end
    end
 
    def destroy
      @vazao_agua_funcionario = VazaoAguaFuncionario.find params[:id]

      @vazao_agua_funcionario.destroy
      flash[:notice] = 'Vazao agua funcionario has been deleted'
      redirect_to casein_vazao_agua_funcionarios_path
    end
  
    private
      
      def vazao_agua_funcionario_params
        params.require(:vazao_agua_funcionario).permit(:vazao_agua_id, :funcionario_id)
      end

  end
end