# Scaffolding generated by Casein v5.1.1.1

module Casein
  class VazoesAguaController < Casein::CaseinController
    load_and_authorize_resource

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
    has_scope :cliente_id

    def index
      @casein_page_title = t('vazoes_agua.index.titulo')

      respond_to do |format|
        format.html
        format.json { render json: VazaoAguaDatatable.new(view_context) }
      end
    end

    def show
      @casein_page_title = t('vazoes_agua.show.titulo')
      @vazao_agua = VazaoAgua.find params[:id]
    end

    def new
      @casein_page_title = t('vazoes_agua.new.titulo')
      @vazao_agua = VazaoAgua.new
      @vazao_agua.vazao_agua_funcionarios.build
      @vazao_agua.arquivos.build
    end

    def create
      @vazao_agua = VazaoAgua.new vazao_agua_params
      if @vazao_agua.save
        flash[:notice] = t('vazoes_agua.create.sucesso', id: @vazao_agua.id)

        if params["avancar"]
          redirect_to new_casein_instalacao_path(poco: @vazao_agua.aprofundamento_id.blank? ? @vazao_agua.poco_id : @vazao_agua.aprofundamento.poco_id, vazao_agua: @vazao_agua.id)
        else
          redirect_to casein_vazao_agua_path(@vazao_agua)
        end
      else
        flash.now[:warning] = t('vazoes_agua.create.alerta')
        render :action => :new
      end
    end

    def edit
      @vazao_agua = VazaoAgua.find params[:id]
      @vazao_agua.vazao_agua_funcionarios.build
      @vazao_agua.arquivos.build
    end

    def update
      @casein_page_title = 'Update vazao agua'

      @vazao_agua = VazaoAgua.find params[:id]

      if @vazao_agua.update_attributes vazao_agua_params
        flash[:notice] = t('vazoes_agua.update.sucesso', id: @vazao_agua.id)

        if params["avancar"]
          if @vazao_agua.aprofundamento_id.blank?
            @instalacao = Instalacao.where(poco_id: @vazao_agua.poco_id).first
          else
            @instalacao = Instalacao.where(aprofundamento_id: @vazao_agua.aprofundamento_id).first
          end            

          if @instalacao.try(:id)
            redirect_to edit_casein_instalacao_path(@instalacao, vazao_agua: @vazao_agua.id)
          else
            if @vazao_agua.aprofundamento_id.blank?
              redirect_to new_casein_instalacao_path(poco: @vazao_agua.poco_id, vazao_agua: @vazao_agua.id)
            else
              redirect_to new_casein_instalacao_path(aprofundamento: @vazao_agua.aprofundamento_id, vazao_agua: @vazao_agua.id)
            end
          end
        else
          redirect_to casein_vazao_agua_path(@vazao_agua)
        end
      else
        flash.now[:warning] = t('vazoes_agua.update.alerta')
        render :action => :edit
      end
    end

    def destroy
      @vazao_agua = VazaoAgua.find params[:id]

      @vazao_agua.destroy
      flash[:notice] = t('vazoes_agua.destroy.sucesso')
      redirect_to casein_vazoes_agua_path
    end

    def filtro_ajax
      @vazoes_agua = apply_scopes(VazaoAgua).order(sort_order(:vazao_teste))
    end

    private

      def vazao_agua_params
        params.require(:vazao_agua).permit(:vazao_teste, :data_teste, :vazao_dinamico, :nivel_estatico, :recuperacao, :poco_id, :aprofundamento_id, :possui_vazao, :observacao, :profundidade_bomba,
                                           vazao_agua_funcionarios_attributes: [:id, :vazao_agua_id, :funcionario_id, :_destroy],
                                           arquivos_attributes: [:id, :owner_id, :owner_type, :upload, :_destroy])
      end

  end
end
